/* GENERATED by scripts/build-icons.mjs from src/icons/icons.json — do not edit.
 * Geometry: Lucide (ISC; Feather-derived: MIT) — THIRD_PARTY_NOTICES.md. */
export default {
  "close": {
    "viewBox": "0 0 24 24",
    "paint": "stroke",
    "nodes": [
      [
        "path",
        {
          "d": "M18 6 6 18"
        }
      ],
      [
        "path",
        {
          "d": "m6 6 12 12"
        }
      ]
    ]
  },
  "check": {
    "viewBox": "0 0 24 24",
    "paint": "stroke",
    "nodes": [
      [
        "path",
        {
          "d": "M20 6 9 17l-5-5"
        }
      ]
    ]
  },
  "prev": {
    "viewBox": "0 0 24 24",
    "paint": "stroke",
    "nodes": [
      [
        "path",
        {
          "d": "m15 18-6-6 6-6"
        }
      ]
    ]
  },
  "next": {
    "viewBox": "0 0 24 24",
    "paint": "stroke",
    "nodes": [
      [
        "path",
        {
          "d": "m9 18 6-6-6-6"
        }
      ]
    ]
  },
  "up": {
    "viewBox": "0 0 24 24",
    "paint": "stroke",
    "nodes": [
      [
        "path",
        {
          "d": "m18 15-6-6-6 6"
        }
      ]
    ]
  },
  "down": {
    "viewBox": "0 0 24 24",
    "paint": "stroke",
    "nodes": [
      [
        "path",
        {
          "d": "m6 9 6 6 6-6"
        }
      ]
    ]
  },
  "back": {
    "viewBox": "0 0 24 24",
    "paint": "stroke",
    "nodes": [
      [
        "path",
        {
          "d": "m15 18-6-6 6-6"
        }
      ]
    ]
  },
  "plus": {
    "viewBox": "0 0 24 24",
    "paint": "stroke",
    "nodes": [
      [
        "path",
        {
          "d": "M5 12h14"
        }
      ],
      [
        "path",
        {
          "d": "M12 5v14"
        }
      ]
    ]
  },
  "minus": {
    "viewBox": "0 0 24 24",
    "paint": "stroke",
    "nodes": [
      [
        "path",
        {
          "d": "M5 12h14"
        }
      ]
    ]
  },
  "more": {
    "viewBox": "0 0 24 24",
    "paint": "stroke",
    "nodes": [
      [
        "circle",
        {
          "cx": "12",
          "cy": "12",
          "r": "1"
        }
      ],
      [
        "circle",
        {
          "cx": "19",
          "cy": "12",
          "r": "1"
        }
      ],
      [
        "circle",
        {
          "cx": "5",
          "cy": "12",
          "r": "1"
        }
      ]
    ]
  },
  "search": {
    "viewBox": "0 0 24 24",
    "paint": "stroke",
    "nodes": [
      [
        "circle",
        {
          "cx": "11",
          "cy": "11",
          "r": "8"
        }
      ],
      [
        "path",
        {
          "d": "m21 21-4.34-4.34"
        }
      ]
    ]
  },
  "calendar": {
    "viewBox": "0 0 24 24",
    "paint": "stroke",
    "nodes": [
      [
        "path",
        {
          "d": "M8 2v4"
        }
      ],
      [
        "path",
        {
          "d": "M16 2v4"
        }
      ],
      [
        "rect",
        {
          "x": "3",
          "y": "4",
          "width": "18",
          "height": "18",
          "rx": "2"
        }
      ],
      [
        "path",
        {
          "d": "M3 10h18"
        }
      ]
    ]
  },
  "fullscreen": {
    "viewBox": "0 0 24 24",
    "paint": "stroke",
    "nodes": [
      [
        "path",
        {
          "d": "M8 3H5a2 2 0 0 0-2 2v3"
        }
      ],
      [
        "path",
        {
          "d": "M21 8V5a2 2 0 0 0-2-2h-3"
        }
      ],
      [
        "path",
        {
          "d": "M3 16v3a2 2 0 0 0 2 2h3"
        }
      ],
      [
        "path",
        {
          "d": "M16 21h3a2 2 0 0 0 2-2v-3"
        }
      ]
    ]
  },
  "download": {
    "viewBox": "0 0 24 24",
    "paint": "stroke",
    "nodes": [
      [
        "path",
        {
          "d": "M12 15V3"
        }
      ],
      [
        "path",
        {
          "d": "M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"
        }
      ],
      [
        "path",
        {
          "d": "m7 10 5 5 5-5"
        }
      ]
    ]
  },
  "external": {
    "viewBox": "0 0 24 24",
    "paint": "stroke",
    "nodes": [
      [
        "path",
        {
          "d": "M15 3h6v6"
        }
      ],
      [
        "path",
        {
          "d": "M10 14 21 3"
        }
      ],
      [
        "path",
        {
          "d": "M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"
        }
      ]
    ]
  },
  "info": {
    "viewBox": "0 0 24 24",
    "paint": "stroke",
    "nodes": [
      [
        "circle",
        {
          "cx": "12",
          "cy": "12",
          "r": "10"
        }
      ],
      [
        "path",
        {
          "d": "M12 16v-4"
        }
      ],
      [
        "path",
        {
          "d": "M12 8h.01"
        }
      ]
    ]
  },
  "success": {
    "viewBox": "0 0 24 24",
    "paint": "stroke",
    "nodes": [
      [
        "path",
        {
          "d": "M21.801 10A10 10 0 1 1 17 3.335"
        }
      ],
      [
        "path",
        {
          "d": "m9 11 3 3L22 4"
        }
      ]
    ]
  },
  "error": {
    "viewBox": "0 0 24 24",
    "paint": "stroke",
    "nodes": [
      [
        "circle",
        {
          "cx": "12",
          "cy": "12",
          "r": "10"
        }
      ],
      [
        "path",
        {
          "d": "M12 8v4"
        }
      ],
      [
        "path",
        {
          "d": "M12 16h.01"
        }
      ]
    ]
  },
  "warning": {
    "viewBox": "0 0 24 24",
    "paint": "stroke",
    "nodes": [
      [
        "path",
        {
          "d": "m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3"
        }
      ],
      [
        "path",
        {
          "d": "M12 9v4"
        }
      ],
      [
        "path",
        {
          "d": "M12 17h.01"
        }
      ]
    ]
  },
  "eye": {
    "viewBox": "0 0 24 24",
    "paint": "stroke",
    "nodes": [
      [
        "path",
        {
          "d": "M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0"
        }
      ],
      [
        "circle",
        {
          "cx": "12",
          "cy": "12",
          "r": "3"
        }
      ]
    ]
  },
  "eye-off": {
    "viewBox": "0 0 24 24",
    "paint": "stroke",
    "nodes": [
      [
        "path",
        {
          "d": "M10.733 5.076a10.744 10.744 0 0 1 11.205 6.575 1 1 0 0 1 0 .696 10.747 10.747 0 0 1-1.444 2.49"
        }
      ],
      [
        "path",
        {
          "d": "M14.084 14.158a3 3 0 0 1-4.242-4.242"
        }
      ],
      [
        "path",
        {
          "d": "M17.479 17.499a10.75 10.75 0 0 1-15.417-5.151 1 1 0 0 1 0-.696 10.75 10.75 0 0 1 4.446-5.143"
        }
      ],
      [
        "path",
        {
          "d": "m2 2 20 20"
        }
      ]
    ]
  },
  "zoom-in": {
    "viewBox": "0 0 24 24",
    "paint": "stroke",
    "nodes": [
      [
        "circle",
        {
          "cx": "11",
          "cy": "11",
          "r": "8"
        }
      ],
      [
        "path",
        {
          "d": "m21 21-4.35-4.35"
        }
      ],
      [
        "path",
        {
          "d": "M11 8v6"
        }
      ],
      [
        "path",
        {
          "d": "M8 11h6"
        }
      ]
    ]
  },
  "inbox": {
    "viewBox": "0 0 24 24",
    "paint": "stroke",
    "nodes": [
      [
        "path",
        {
          "d": "M22 12h-6l-2 3h-4l-2-3H2"
        }
      ],
      [
        "path",
        {
          "d": "M5.45 5.11 2 12v6a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-6l-3.45-6.89A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z"
        }
      ]
    ]
  },
  "star": {
    "viewBox": "0 0 24 24",
    "paint": "stroke",
    "nodes": [
      [
        "path",
        {
          "d": "M11.525 2.295a.53.53 0 0 1 .95 0l2.31 4.679a2.123 2.123 0 0 0 1.595 1.16l5.166.756a.53.53 0 0 1 .294.904l-3.736 3.638a2.123 2.123 0 0 0-.611 1.878l.882 5.14a.53.53 0 0 1-.771.56l-4.618-2.428a2.122 2.122 0 0 0-1.973 0L6.396 21.01a.53.53 0 0 1-.77-.56l.881-5.139a2.122 2.122 0 0 0-.611-1.879L2.16 9.795a.53.53 0 0 1 .294-.906l5.165-.755a2.122 2.122 0 0 0 1.597-1.16z"
        }
      ]
    ]
  },
  "upload": {
    "viewBox": "0 0 24 24",
    "paint": "stroke",
    "nodes": [
      [
        "path",
        {
          "d": "M12 3v12"
        }
      ],
      [
        "path",
        {
          "d": "m17 8-5-5-5 5"
        }
      ],
      [
        "path",
        {
          "d": "M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"
        }
      ]
    ]
  },
  "link": {
    "viewBox": "0 0 24 24",
    "paint": "stroke",
    "nodes": [
      [
        "path",
        {
          "d": "M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"
        }
      ],
      [
        "path",
        {
          "d": "M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"
        }
      ]
    ]
  },
  "image": {
    "viewBox": "0 0 24 24",
    "paint": "stroke",
    "nodes": [
      [
        "rect",
        {
          "x": "3",
          "y": "3",
          "width": "18",
          "height": "18",
          "rx": "2",
          "ry": "2"
        }
      ],
      [
        "circle",
        {
          "cx": "9",
          "cy": "9",
          "r": "2"
        }
      ],
      [
        "path",
        {
          "d": "m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21"
        }
      ]
    ]
  },
  "sort": {
    "viewBox": "0 0 24 24",
    "paint": "stroke",
    "nodes": [
      [
        "path",
        {
          "d": "m7 15 5 5 5-5"
        }
      ],
      [
        "path",
        {
          "d": "m7 9 5-5 5 5"
        }
      ]
    ]
  },
  "trash": {
    "viewBox": "0 0 24 24",
    "paint": "stroke",
    "nodes": [
      [
        "path",
        {
          "d": "M10 11v6"
        }
      ],
      [
        "path",
        {
          "d": "M14 11v6"
        }
      ],
      [
        "path",
        {
          "d": "M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6"
        }
      ],
      [
        "path",
        {
          "d": "M3 6h18"
        }
      ],
      [
        "path",
        {
          "d": "M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"
        }
      ]
    ]
  },
  "pencil": {
    "viewBox": "0 0 24 24",
    "paint": "stroke",
    "nodes": [
      [
        "path",
        {
          "d": "M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z"
        }
      ],
      [
        "path",
        {
          "d": "m15 5 4 4"
        }
      ]
    ]
  },
  "copy": {
    "viewBox": "0 0 24 24",
    "paint": "stroke",
    "nodes": [
      [
        "rect",
        {
          "width": "14",
          "height": "14",
          "x": "8",
          "y": "8",
          "rx": "2",
          "ry": "2"
        }
      ],
      [
        "path",
        {
          "d": "M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"
        }
      ]
    ]
  },
  "log-out": {
    "viewBox": "0 0 24 24",
    "paint": "stroke",
    "nodes": [
      [
        "path",
        {
          "d": "m16 17 5-5-5-5"
        }
      ],
      [
        "path",
        {
          "d": "M21 12H9"
        }
      ],
      [
        "path",
        {
          "d": "M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"
        }
      ]
    ]
  },
  "menu": {
    "viewBox": "0 0 24 24",
    "paint": "stroke",
    "nodes": [
      [
        "path",
        {
          "d": "M4 5h16"
        }
      ],
      [
        "path",
        {
          "d": "M4 12h16"
        }
      ],
      [
        "path",
        {
          "d": "M4 19h16"
        }
      ]
    ]
  },
  "rotate-cw": {
    "viewBox": "0 0 24 24",
    "paint": "stroke",
    "nodes": [
      [
        "path",
        {
          "d": "M21 12a9 9 0 1 1-9-9c2.52 0 4.93 1 6.74 2.74L21 8"
        }
      ],
      [
        "path",
        {
          "d": "M21 3v5h-5"
        }
      ]
    ]
  },
  "zoom-out": {
    "viewBox": "0 0 24 24",
    "paint": "stroke",
    "nodes": [
      [
        "circle",
        {
          "cx": "11",
          "cy": "11",
          "r": "8"
        }
      ],
      [
        "path",
        {
          "d": "m21 21-4.35-4.35"
        }
      ],
      [
        "path",
        {
          "d": "M8 11h6"
        }
      ]
    ]
  },
  "grip": {
    "viewBox": "0 0 24 24",
    "paint": "stroke",
    "nodes": [
      [
        "circle",
        {
          "cx": "9",
          "cy": "12",
          "r": "1"
        }
      ],
      [
        "circle",
        {
          "cx": "9",
          "cy": "5",
          "r": "1"
        }
      ],
      [
        "circle",
        {
          "cx": "9",
          "cy": "19",
          "r": "1"
        }
      ],
      [
        "circle",
        {
          "cx": "15",
          "cy": "12",
          "r": "1"
        }
      ],
      [
        "circle",
        {
          "cx": "15",
          "cy": "5",
          "r": "1"
        }
      ],
      [
        "circle",
        {
          "cx": "15",
          "cy": "19",
          "r": "1"
        }
      ]
    ]
  },
  "video": {
    "viewBox": "0 0 24 24",
    "paint": "stroke",
    "nodes": [
      [
        "path",
        {
          "d": "m16 13 5.223 3.482a.5.5 0 0 0 .777-.416V7.87a.5.5 0 0 0-.752-.432L16 10.5"
        }
      ],
      [
        "rect",
        {
          "x": "2",
          "y": "6",
          "width": "14",
          "height": "12",
          "rx": "2"
        }
      ]
    ]
  },
  "file": {
    "viewBox": "0 0 24 24",
    "paint": "stroke",
    "nodes": [
      [
        "path",
        {
          "d": "M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z"
        }
      ],
      [
        "path",
        {
          "d": "M14 2v4a2 2 0 0 0 2 2h4"
        }
      ]
    ]
  },
  "filter": {
    "viewBox": "0 0 24 24",
    "paint": "stroke",
    "nodes": [
      [
        "line",
        {
          "x1": "21",
          "x2": "14",
          "y1": "4",
          "y2": "4"
        }
      ],
      [
        "line",
        {
          "x1": "10",
          "x2": "3",
          "y1": "4",
          "y2": "4"
        }
      ],
      [
        "line",
        {
          "x1": "21",
          "x2": "12",
          "y1": "12",
          "y2": "12"
        }
      ],
      [
        "line",
        {
          "x1": "8",
          "x2": "3",
          "y1": "12",
          "y2": "12"
        }
      ],
      [
        "line",
        {
          "x1": "21",
          "x2": "16",
          "y1": "20",
          "y2": "20"
        }
      ],
      [
        "line",
        {
          "x1": "12",
          "x2": "3",
          "y1": "20",
          "y2": "20"
        }
      ],
      [
        "line",
        {
          "x1": "14",
          "x2": "14",
          "y1": "2",
          "y2": "6"
        }
      ],
      [
        "line",
        {
          "x1": "8",
          "x2": "8",
          "y1": "10",
          "y2": "14"
        }
      ],
      [
        "line",
        {
          "x1": "16",
          "x2": "16",
          "y1": "18",
          "y2": "22"
        }
      ]
    ]
  }
};

/** Alternative name → core icon name (icons.json "aliases"). */
export const aliases = {
  "x": "close",
  "chevron-left": "prev",
  "chevron-right": "next",
  "chevron-up": "up",
  "chevron-down": "down",
  "ellipsis": "more",
  "external-link": "external",
  "expand": "fullscreen",
  "pen": "pencil"
};
