<?php
/**
 * v0.36.0 — HTML fixture of src/form/td-action-button.ssr.engines.browser-test.js: td_action_button() in ELEMENT mode for
 * every preset of Td::ACTION_PRESETS (`preset-{name}`) + every case of test/ssr/action-button.fixtures.json, each in its
 * own `<section class="ssr-case" data-case="…">`. Regenerate with `node test/ssr/build-action-button-fixture.mjs`
 * (test/php/td-action-button.test.js fails when test/ssr/fixtures/action-button.html is stale).
 */
declare(strict_types=1);

require __DIR__ . '/../../php/td.php';

use TdComponents\Td;

Td::configure('/', dirname(__DIR__, 2));
$spec = json_decode((string) file_get_contents(__DIR__ . '/action-button.fixtures.json'), true, 64, JSON_THROW_ON_ERROR);

$cases = [];
foreach (array_keys(Td::ACTION_PRESETS) as $name) {
    $cases[] = ['id' => 'preset-' . $name, 'action' => $name, 'o' => []];
}
foreach ($spec['cases'] as $case) {
    $cases[] = $case;
}

echo "<!-- GENERATED by test/ssr/build-action-button-fixture.mjs from test/ssr/action-button-fixture.php (php/td.php) — do not edit by hand. -->\n";
foreach ($cases as $case) {
    echo '<section class="ssr-case" data-case="', Td::e($case['id']), '">',
        td_action_button($case['action'], $case['o'] + ['element' => true]), "</section>\n";
}
