<?php
/**
 * v0.55.0 — HTML fixture of src/form/td-v055-affix.ssr.engines.browser-test.js: every case of test/ssr/affix.fixtures.json
 * (td_field / td_number_input with prefix / suffix / icons / unit_label / locale) rendered by php/td.php, each inside its
 * own `<form class="ssr-case" data-case="…">`. Regenerate with `node test/ssr/build-affix-fixture.mjs`
 * (test/php/td-v055-php.test.js fails when it is stale).
 */
declare(strict_types=1);

require __DIR__ . '/../../php/td.php';

use TdComponents\Td;

Td::configure('/', dirname(__DIR__, 2));
$spec = json_decode((string) file_get_contents(__DIR__ . '/affix.fixtures.json'), true, 64, JSON_THROW_ON_ERROR);

echo "<!-- GENERATED by test/ssr/build-affix-fixture.mjs from test/ssr/affix-fixture.php (php/td.php) — do not edit by hand. -->\n";
foreach ($spec['cases'] as $case) {
    echo '<form class="ssr-case" data-case="', Td::e($case['id']), '" action="/__ssr-submit" method="post">',
        $case['fn'](...$case['args']), "</form>\n";
}
