<?php
/**
 * v0.25.0 — HTML fixture of src/form/td-button.ssr.browser-test.js: every case of test/ssr/button.fixtures.json
 * rendered by php/td.php in ELEMENT mode (per call `element => true`, or `global` → Td::configure(..., ['ssr_elements'
 * => true])), each inside its own `<form class="ssr-case" data-case="…">`. Regenerate with
 * `node test/ssr/build-button-fixture.mjs` (test/php/td-ssr.test.js fails when test/ssr/fixtures/button.html is stale).
 */
declare(strict_types=1);

require __DIR__ . '/../../php/td.php';

use TdComponents\Td;

$kit = dirname(__DIR__, 2);
$spec = json_decode((string) file_get_contents(__DIR__ . '/button.fixtures.json'), true, 64, JSON_THROW_ON_ERROR);

/** Render one fixture case (the options are the LAST argument). */
function ssr_case(array $case, string $kit): string
{
    $args = $case['args'];
    $last = count($args) - 1;
    if (!empty($case['global'])) {
        Td::configure('/', $kit, ['ssr_elements' => true]);
    } else {
        Td::configure('/', $kit);
        $args[$last]['element'] = true;
    }
    $html = $case['fn'](...$args);
    Td::configure('/', $kit);
    return $html;
}

echo "<!-- GENERATED by test/ssr/build-button-fixture.mjs from test/ssr/button-fixture.php (php/td.php) — do not edit by hand. -->\n";
foreach ($spec['cases'] as $case) {
    echo '<form class="ssr-case" data-case="', Td::e($case['id']), '" action="/__ssr-submit" method="post">',
        ssr_case($case, $kit), "</form>\n";
}
