<?php
/**
 * v0.50.0 — HTML fixture of src/display/td-v050-carousel.engines.browser-test.js (+ the responsive / touch gates): every
 * case of test/ssr/carousel.fixtures.json rendered by td_carousel() (always the element), each inside its own
 * `<section class="ssr-case" data-case="…">`. Regenerate with `node test/ssr/build-carousel-fixture.mjs`
 * (test/php/td-ssr-carousel.test.js fails when test/ssr/fixtures/carousel.html is stale).
 */
declare(strict_types=1);

require __DIR__ . '/../../php/td.php';

use TdComponents\Td;

Td::configure('/', dirname(__DIR__, 2));
$spec = json_decode((string) file_get_contents(__DIR__ . '/carousel.fixtures.json'), true, 64, JSON_THROW_ON_ERROR);

echo "<!-- GENERATED by test/ssr/build-carousel-fixture.mjs from test/ssr/carousel-fixture.php (php/td.php) — do not edit by hand. -->\n";
// a slide {"html": …} is trusted markup of the fixture (Td::html); a plain string would be escaped (Codex review S1)
foreach ($spec['cases'] as $case) {
    $case['args'][0] = array_map(static fn ($s) => is_array($s) && array_keys($s) === ['html'] ? Td::html((string) $s['html']) : $s, $case['args'][0]);
    echo '<section class="ssr-case" data-case="', Td::e($case['id']), '">', td_carousel(...$case['args']), "</section>\n";
}
