<?php
/**
 * v0.47.0 — HTML fixture of src/form/td-check-matrix.ssr.engines.browser-test.js: every case of
 * test/ssr/check-matrix.fixtures.json rendered by td_check_matrix(), each inside its own
 * `<form class="ssr-case" data-case="…">`. Regenerate with `node test/ssr/build-check-matrix-fixture.mjs`
 * (test/php/td-ssr-check-matrix.test.js fails when the file is stale). Fail-closed cases warn: muted here on purpose.
 */
declare(strict_types=1);

require __DIR__ . '/../../php/td.php';

use TdComponents\Td;

Td::configure('/', dirname(__DIR__, 2));
$spec = json_decode((string) file_get_contents(__DIR__ . '/check-matrix.fixtures.json'), true, 64, JSON_THROW_ON_ERROR);

echo "<!-- GENERATED by test/ssr/build-check-matrix-fixture.mjs from test/ssr/check-matrix-fixture.php (php/td.php) — do not edit by hand. -->\n";
foreach ($spec['cases'] as $case) {
    echo '<form class="ssr-case" data-case="', Td::e($case['id']), '" action="/__ssr-submit" method="post">',
        @td_check_matrix(...$case['args']), "</form>\n";
}
