<?php
/**
 * v0.49.0 — HTML fixture of src/form/td-choice-group.ssr.engines.browser-test.js: every case of
 * test/ssr/choice.fixtures.json rendered by td_choice_group() (always the element), each inside its own
 * `<form class="ssr-case" data-case="…">`. A case with `allowHttp` is printed after Td::allowHttpLinks(true). Regenerate
 * with `node test/ssr/build-choice-fixture.mjs` (test/php/td-ssr-choice.test.js fails when the file is stale).
 */
declare(strict_types=1);

require __DIR__ . '/../../php/td.php';

use TdComponents\Td;

Td::configure('/', dirname(__DIR__, 2));
$spec = json_decode((string) file_get_contents(__DIR__ . '/choice.fixtures.json'), true, 64, JSON_THROW_ON_ERROR);

echo "<!-- GENERATED by test/ssr/build-choice-fixture.mjs from test/ssr/choice-fixture.php (php/td.php) — do not edit by hand. -->\n";
foreach ($spec['cases'] as $case) {
    Td::allowHttpLinks(!empty($case['allowHttp']));
    echo '<form class="ssr-case" data-case="', Td::e($case['id']), '" action="/__ssr-submit" method="post">',
        td_choice_group(...$case['args']), "</form>\n";
}
Td::allowHttpLinks(false);
