<?php
/**
 * v0.48.0 — HTML fixture of src/form/td-color-picker.ssr.engines.browser-test.js: every case of
 * test/ssr/color-picker.fixtures.json rendered by td_color_picker(), each inside its own
 * `<form class="ssr-case|ssr-native" data-case="…">`. Regenerate with `node test/ssr/build-color-picker-fixture.mjs`
 * (test/php/td-ssr-color.test.js fails when the file is stale).
 */
declare(strict_types=1);

require __DIR__ . '/../../php/td.php';

use TdComponents\Td;

Td::configure('/', dirname(__DIR__, 2));
$spec = json_decode((string) file_get_contents(__DIR__ . '/color-picker.fixtures.json'), true, 64, JSON_THROW_ON_ERROR);

echo "<!-- GENERATED by test/ssr/build-color-picker-fixture.mjs from test/ssr/color-picker-fixture.php (php/td.php) — do not edit by hand. -->\n";
foreach (['cases' => 'ssr-case', 'nativeCases' => 'ssr-native'] as $key => $class) {
    foreach ($spec[$key] as $case) {
        echo '<form class="', $class, '" data-case="', Td::e($case['id']), '" action="/__ssr-submit" method="post">',
            td_color_picker(...$case['args']), "</form>\n";
    }
}
