<?php
/**
 * v0.27.0 — HTML fixture of src/display/td-copy.ssr.engines.browser-test.js: every case of test/ssr/copy.fixtures.json rendered
 * by td_copy() (always element mode), each inside its own `<section class="ssr-case" data-case="…">`. Regenerate with
 * `node test/ssr/build-otp-copy-fixture.mjs` (test/php/td-ssr-otp-copy.test.js fails when test/ssr/fixtures/copy.html
 * is stale).
 */
declare(strict_types=1);

require __DIR__ . '/../../php/td.php';

use TdComponents\Td;

Td::configure('/', dirname(__DIR__, 2));
$spec = json_decode((string) file_get_contents(__DIR__ . '/copy.fixtures.json'), true, 64, JSON_THROW_ON_ERROR);

echo "<!-- GENERATED by test/ssr/build-otp-copy-fixture.mjs from test/ssr/copy-fixture.php (php/td.php) — do not edit by hand. -->\n";
foreach ($spec['cases'] as $case) {
    echo '<section class="ssr-case" data-case="', Td::e($case['id']), '">', td_copy(...$case['args']), "</section>\n";
}
