<?php
/**
 * v0.40.0 — HTML fixture of src/form/td-datetime-range.ssr.engines.browser-test.js: every case of
 * test/ssr/datetime-range.fixtures.json rendered by td_datetime_range(), each inside its own
 * `<form class="ssr-case" data-case="…">`. Regenerate with `node test/ssr/build-datetime-range-fixture.mjs`
 * (test/php/td-ssr-datetime-range.test.js fails when the file is stale).
 */
declare(strict_types=1);

require __DIR__ . '/../../php/td.php';

use TdComponents\Td;

Td::configure('/', dirname(__DIR__, 2));
$spec = json_decode((string) file_get_contents(__DIR__ . '/datetime-range.fixtures.json'), true, 64, JSON_THROW_ON_ERROR);

echo "<!-- GENERATED by test/ssr/build-datetime-range-fixture.mjs from test/ssr/datetime-range-fixture.php (php/td.php) — do not edit by hand. -->\n";
foreach ($spec['cases'] as $case) {
    echo '<form class="ssr-case" data-case="', Td::e($case['id']), '" action="/__ssr-submit" method="post">',
        td_datetime_range(...$case['args']), "</form>\n";
}
