<?php
/**
 * v0.56.0 — HTML fixture of src/form/td-datetime-picker.ssr.engines.browser-test.js: every case of
 * test/ssr/datetime-picker.fixtures.json rendered by td_datetime_picker() / td_date(), each inside its own
 * `<form class="ssr-case" data-case="…">`. Regenerate with `node test/ssr/build-datetime-picker-fixture.mjs`
 * (test/php/td-v056-php.test.js fails when the file is stale). A `quiet` case warns on purpose (silenced here).
 */
declare(strict_types=1);

require __DIR__ . '/../../php/td.php';

use TdComponents\Td;

Td::configure('/', dirname(__DIR__, 2));
$spec = json_decode((string) file_get_contents(__DIR__ . '/datetime-picker.fixtures.json'), true, 64, JSON_THROW_ON_ERROR);

echo "<!-- GENERATED by test/ssr/build-datetime-picker-fixture.mjs from test/ssr/datetime-picker-fixture.php (php/td.php) — do not edit by hand. -->\n";
foreach ($spec['cases'] as $case) {
    $fn = $case['fn'] === 'td_date' ? 'td_date' : 'td_datetime_picker';
    if (!empty($case['quiet'])) {
        set_error_handler(static fn (int $no): bool => $no === E_USER_WARNING);
    }
    $html = $fn(...$case['args']);
    if (!empty($case['quiet'])) {
        restore_error_handler();
    }
    echo '<form class="ssr-case" data-case="', Td::e($case['id']), '" action="/__ssr-submit" method="post">', $html, "</form>\n";
}
