<?php
/**
 * v0.46.0 — HTML fixture of src/display/td-diff.ssr.engines.browser-test.js: every case of test/ssr/diff.fixtures.json
 * rendered by td_diff() / td_diff_snapshots() (always the element, contract diff@1), each inside its own
 * `<section class="ssr-case" data-case="…">`. Regenerate with `node test/ssr/build-diff-fixture.mjs`
 * (test/php/td-ssr-diff.test.js fails when test/ssr/fixtures/diff.html is stale).
 */
declare(strict_types=1);

require __DIR__ . '/../../php/td.php';

use TdComponents\Td;

Td::configure('/', dirname(__DIR__, 2));
$spec = json_decode((string) file_get_contents(__DIR__ . '/diff.fixtures.json'), false, 512, JSON_THROW_ON_ERROR);
set_error_handler(static fn (int $no, string $msg): bool => $no === E_USER_WARNING && str_starts_with($msg, 'td_diff'));

echo "<!-- GENERATED by test/ssr/build-diff-fixture.mjs from test/ssr/diff-fixture.php (php/td.php) — do not edit by hand. -->\n";
foreach ($spec->cases as $c) {
    $opts = json_decode(json_encode($c->opts, JSON_THROW_ON_ERROR), true, 512, JSON_THROW_ON_ERROR);
    if ($c->mode === 'items') {
        $html = td_diff($c->items, $opts);
    } else {
        $opts['fields'] = $c->fields ?? null;
        $html = td_diff_snapshots($c->before, $c->after, $opts);
    }
    echo '<section class="ssr-case" data-case="', Td::e($c->id), '">', $html, "</section>\n";
}
