<?php
/**
 * v0.26.0 (part 2) — HTML fixture of src/form/td-dropdown.ssr.browser-test.js: every case of
 * test/ssr/dropdown.fixtures.json rendered by php/td.php in ELEMENT mode (per call `element => true`, or `global` →
 * Td::configure(..., ['ssr_elements' => true])), each inside its own `<form class="ssr-case" data-case="…">`;
 * `externalLabel` → a `<label class="ext-label" for="{id}-select">` before the helper. Regenerate with
 * `node test/ssr/build-dropdown-empty-fixture.mjs` (test/php/td-ssr-dropdown-empty.test.js fails when
 * test/ssr/fixtures/dropdown.html is stale).
 */
declare(strict_types=1);

require __DIR__ . '/../../php/td.php';

use TdComponents\Td;

$kit = dirname(__DIR__, 2);
$spec = json_decode((string) file_get_contents(__DIR__ . '/dropdown.fixtures.json'), true, 64, JSON_THROW_ON_ERROR);

/** Render one fixture case (the options are the LAST argument). */
function ssr_dropdown_case(array $case, string $kit): string
{
    $args = $case['args'];
    $last = count($args) - 1;
    if (!empty($case['global'])) {
        Td::configure('/', $kit, ['ssr_elements' => true]);
    } else {
        Td::configure('/', $kit);
        $args[$last]['element'] = true;
    }
    $html = $case['fn'](...$args);
    Td::configure('/', $kit);
    return $html;
}

echo "<!-- GENERATED by test/ssr/build-dropdown-empty-fixture.mjs from test/ssr/dropdown-fixture.php (php/td.php) — do not edit by hand. -->\n";
foreach ($spec['cases'] as $case) {
    $ext = isset($case['externalLabel'])
        ? '<label class="ext-label" for="' . Td::e((string) $case['args'][count($case['args']) - 1]['id']) . '-select">'
            . Td::e((string) $case['externalLabel']) . '</label>'
        : '';
    echo '<form class="ssr-case" data-case="', Td::e($case['id']), '" action="/__ssr-submit" method="post">',
        $ext, ssr_dropdown_case($case, $kit), "</form>\n";
}
