<?php
/**
 * v0.39.0 — HTML fixture of src/display/td-filter-chips.ssr.engines.browser-test.js: every case of
 * test/ssr/filter-chips.fixtures.json rendered by td_filter_chips() (always element mode), each inside its own
 * `<section class="ssr-case" data-case="…">`. Regenerate with `node test/ssr/build-filter-chips-fixture.mjs`
 * (test/php/td-ssr-filter-chips.test.js fails when test/ssr/fixtures/filter-chips.html is stale).
 */
declare(strict_types=1);

require __DIR__ . '/../../php/td.php';

use TdComponents\Td;

Td::configure('/', dirname(__DIR__, 2));
$spec = json_decode((string) file_get_contents(__DIR__ . '/filter-chips.fixtures.json'), true, 64, JSON_THROW_ON_ERROR);

echo "<!-- GENERATED by test/ssr/build-filter-chips-fixture.mjs from test/ssr/filter-chips-fixture.php (php/td.php) — do not edit by hand. -->\n";
foreach ($spec['cases'] as $case) {
    echo '<section class="ssr-case" data-case="', Td::e($case['id']), '">', td_filter_chips(...$case['args']), "</section>\n";
}
