<?php
/**
 * v0.58.0 — HTML fixture of src/form/td-v058-floating.ssr.engines.browser-test.js: every case of
 * test/ssr/floating.fixtures.json (td_field with label_mode=floating) rendered by php/td.php, each inside its own
 * `<form class="ssr-case" data-case="…">`. Regenerate with `node test/ssr/build-floating-fixture.mjs`
 * (test/php/td-v058-php.test.js fails when it is stale).
 */
declare(strict_types=1);

require __DIR__ . '/../../php/td.php';

use TdComponents\Td;

Td::configure('/', dirname(__DIR__, 2));
$spec = json_decode((string) file_get_contents(__DIR__ . '/floating.fixtures.json'), true, 64, JSON_THROW_ON_ERROR);

echo "<!-- GENERATED by test/ssr/build-floating-fixture.mjs from test/ssr/floating-fixture.php (php/td.php) — do not edit by hand. -->\n";
foreach ($spec['cases'] as $case) {
    echo '<form class="ssr-case" data-case="', Td::e($case['id']), '" action="/__ssr-submit" method="post">',
        $case['fn'](...$case['args']), "</form>\n";
}
