<?php
/**
 * v0.51.1 (plan v0.51.1-ssr-fouc, ADR 0025) — HTML fixture of test/engines/ssr-fouc.spec.mjs: every case of
 * test/ssr/fouc.fixtures.json rendered by php/td.php (helper default = native, or per call `element`), one
 * `<section class="fouc-case" …>` per line carrying the case id / kind / module / container width / host tag.
 * Regenerate with `node test/ssr/build-fouc-fixture.mjs` (test/php/td-ssr-fouc.test.js fails when
 * test/ssr/fixtures/fouc.html is stale).
 */
declare(strict_types=1);

require __DIR__ . '/../../php/td.php';

use TdComponents\Td;

$kit = dirname(__DIR__, 2);
Td::configure('/', $kit);
$spec = json_decode((string) file_get_contents(__DIR__ . '/fouc.fixtures.json'), true, 64, JSON_THROW_ON_ERROR);

/** Render one case: `@tree` references, trusted slides, per-call element mode (options = the LAST array argument). */
function fouc_case(array $case, array $trees): string
{
    $args = array_map(static fn ($a) => is_string($a) && str_starts_with($a, '@') ? $trees[substr($a, 1)] : $a, $case['args']);
    if ($case['fn'] === 'td_carousel') {
        $args[0] = array_map(static fn ($s) => is_array($s) && array_keys($s) === ['html'] ? Td::html((string) $s['html']) : $s, $args[0]);
    }
    if (array_key_exists('element', $case)) {
        $last = count($args) - 1;
        if (!is_array($args[$last])) {
            $args[] = [];
            $last++;
        }
        $args[$last]['element'] = (bool) $case['element'];
    }
    return $case['fn'](...$args);
}

echo "<!-- GENERATED by test/ssr/build-fouc-fixture.mjs from test/ssr/fouc-fixture.php (php/td.php) — do not edit by hand. -->\n";
foreach ($spec['cases'] as $case) {
    $html = fouc_case($case, $spec['trees']);
    preg_match('/^<([a-z0-9-]+)/', $html, $m);
    echo '<section class="fouc-case" data-case="', Td::e($case['id']), '" data-kind="', Td::e($case['kind']),
        '" data-module="', Td::e($case['module']), '" data-width="', (int) $case['width'], '" data-tag="', Td::e($m[1] ?? ''), '">',
        $html, "</section>\n";
}
