<?php
/**
 * v0.54.0 — HTML fixture of src/base/td-v054-hint.ssr.engines.browser-test.js: every case of test/ssr/hint.fixtures.json
 * (helper_text on each td_* form helper + td_hint) rendered by php/td.php, each inside its own
 * `<form class="ssr-case" data-case="…">`. `td_hint_trusted` = td_hint($for, Td::html($markup)).
 * Regenerate with `node test/ssr/build-hint-fixture.mjs` (test/php/td-v054-php.test.js fails when it is stale).
 */
declare(strict_types=1);

require __DIR__ . '/../../php/td.php';

use TdComponents\Td;

Td::configure('/', dirname(__DIR__, 2));
$spec = json_decode((string) file_get_contents(__DIR__ . '/hint.fixtures.json'), true, 64, JSON_THROW_ON_ERROR);

echo "<!-- GENERATED by test/ssr/build-hint-fixture.mjs from test/ssr/hint-fixture.php (php/td.php) — do not edit by hand. -->\n";
foreach ($spec['cases'] as $case) {
    echo '<form class="ssr-case" data-case="', Td::e($case['id']), '" action="/__ssr-submit" method="post">',
        $case['fn'](...$case['args']), "</form>\n";
}
foreach ($spec['hints'] as $case) {
    $html = $case['fn'] === 'td_hint_trusted'
        ? td_hint($case['args'][0], Td::html($case['args'][1]))
        : td_hint(...$case['args']);
    echo '<div class="ssr-case" data-case="', Td::e($case['id']), '">', $case['control'], $html, "</div>\n";
}
