<?php
/**
 * v0.31.0 — HTML fixture of src/display/td-masked-value.ssr.engines.browser-test.js: every case of
 * test/ssr/masked-value.fixtures.json rendered by td_masked_value() (always element mode), each inside its own
 * `<section class="ssr-case" data-case="…">`. Regenerate with `node test/ssr/build-masked-value-fixture.mjs`
 * (test/php/td-ssr-masked-value.test.js fails when test/ssr/fixtures/masked-value.html is stale).
 */
declare(strict_types=1);

require __DIR__ . '/../../php/td.php';

use TdComponents\Td;

Td::configure('/', dirname(__DIR__, 2));
$spec = json_decode((string) file_get_contents(__DIR__ . '/masked-value.fixtures.json'), true, 64, JSON_THROW_ON_ERROR);

echo "<!-- GENERATED by test/ssr/build-masked-value-fixture.mjs from test/ssr/masked-value-fixture.php (php/td.php) — do not edit by hand. -->\n";
foreach ($spec['cases'] as $case) {
    echo '<section class="ssr-case" data-case="', Td::e($case['id']), '">', td_masked_value(...$case['args']), "</section>\n";
}
