<?php
/**
 * v0.32.0 — HTML fixture of src/form/td-media-field.ssr.engines.browser-test.js: every case of
 * test/ssr/media-field.fixtures.json rendered by td_media_field() (always element mode), each inside its own
 * `<form class="ssr-case" data-case="…">`. The E_USER_WARNING of the cases marked `warns` is silenced here (counted by
 * test/php/td-ssr-media-field.test.js). Regenerate with `node test/ssr/build-media-field-fixture.mjs` (the PHP test
 * fails when test/ssr/fixtures/media-field.html is stale).
 */
declare(strict_types=1);

require __DIR__ . '/../../php/td.php';

use TdComponents\Td;

Td::configure('/', dirname(__DIR__, 2));
$spec = json_decode((string) file_get_contents(__DIR__ . '/media-field.fixtures.json'), true, 64, JSON_THROW_ON_ERROR);

echo "<!-- GENERATED by test/ssr/build-media-field-fixture.mjs from test/ssr/media-field-fixture.php (php/td.php) — do not edit by hand. -->\n";
foreach ($spec['cases'] as $case) {
    set_error_handler(static fn (int $no): bool => !empty($case['warns']) && $no === E_USER_WARNING);
    $html = td_media_field(...$case['args']);
    restore_error_handler();
    echo '<form class="ssr-case" data-case="', Td::e($case['id']), '" action="/__ssr-submit" method="post">', $html, "</form>\n";
}
