<?php
/**
 * v0.28.0 — HTML fixture of src/form/td-v028-multiselect.engines.browser-test.js: every case of
 * test/ssr/multiselect.fixtures.json rendered by td_multiselect() in ELEMENT mode (per call `element => true`, or
 * `global` → Td::configure(..., ['ssr_elements' => true])), each inside its own `<form class="ssr-case" data-case="…">`,
 * plus the native cases (`<form class="ssr-native" …>`, default mode). Regenerate with
 * `node test/ssr/build-multiselect-fixture.mjs` (test/php/td-ssr-multiselect.test.js fails when
 * test/ssr/fixtures/multiselect.html is stale).
 */
declare(strict_types=1);

require __DIR__ . '/../../php/td.php';

use TdComponents\Td;

$kit = dirname(__DIR__, 2);
$spec = json_decode((string) file_get_contents(__DIR__ . '/multiselect.fixtures.json'), true, 64, JSON_THROW_ON_ERROR);

/** Render one element-mode case (the options are the LAST argument). */
function ssr_multiselect_case(array $case, string $kit): string
{
    $args = $case['args'];
    $last = count($args) - 1;
    if (!empty($case['global'])) {
        Td::configure('/', $kit, ['ssr_elements' => true]);
    } else {
        Td::configure('/', $kit);
        $args[$last]['element'] = true;
    }
    $html = td_multiselect(...$args);
    Td::configure('/', $kit);
    return $html;
}

Td::configure('/', $kit);
echo "<!-- GENERATED by test/ssr/build-multiselect-fixture.mjs from test/ssr/multiselect-fixture.php (php/td.php) — do not edit by hand. -->\n";
foreach ($spec['cases'] as $case) {
    echo '<form class="ssr-case" data-case="', Td::e($case['id']), '" action="/__ssr-submit" method="post">',
        ssr_multiselect_case($case, $kit), "</form>\n";
}
foreach ($spec['nativeCases'] as $case) {
    echo '<form class="ssr-native" data-case="', Td::e($case['id']), '" action="/__ssr-submit" method="post">',
        td_multiselect(...$case['args']), "</form>\n";
}
