<?php
/**
 * v0.27.0 — HTML fixture of src/form/td-otp-input.ssr.engines.browser-test.js: every case of test/ssr/otp.fixtures.json rendered
 * by td_otp_input() (the cases carry `element => true`), each inside its own `<form class="ssr-case" data-case="…">`,
 * plus the native cases (`<form class="ssr-native" …>`). Regenerate with `node test/ssr/build-otp-copy-fixture.mjs`
 * (test/php/td-ssr-otp-copy.test.js fails when test/ssr/fixtures/otp.html is stale).
 */
declare(strict_types=1);

require __DIR__ . '/../../php/td.php';

use TdComponents\Td;

Td::configure('/', dirname(__DIR__, 2));
$spec = json_decode((string) file_get_contents(__DIR__ . '/otp.fixtures.json'), true, 64, JSON_THROW_ON_ERROR);

echo "<!-- GENERATED by test/ssr/build-otp-copy-fixture.mjs from test/ssr/otp-fixture.php (php/td.php) — do not edit by hand. -->\n";
foreach ($spec['cases'] as $case) {
    echo '<form class="ssr-case" data-case="', Td::e($case['id']), '" action="/__ssr-submit" method="post">',
        td_otp_input(...$case['args']), "</form>\n";
}
foreach ($spec['nativeCases'] as $case) {
    echo '<form class="ssr-native" data-case="', Td::e($case['id']), '" action="/__ssr-submit" method="post">',
        td_otp_input(...$case['args']), "</form>\n";
}
