<?php
/**
 * v0.50.0 — HTML fixture of src/display/td-v050-rating.engines.browser-test.js: every case of test/ssr/rating.fixtures.json
 * rendered by td_rating() (always the element), each inside its own `<section class="ssr-case" data-case="…">`.
 * Regenerate with `node test/ssr/build-rating-fixture.mjs` (test/php/td-ssr-rating.test.js fails when
 * test/ssr/fixtures/rating.html is stale).
 */
declare(strict_types=1);

require __DIR__ . '/../../php/td.php';

use TdComponents\Td;

Td::configure('/', dirname(__DIR__, 2));
$spec = json_decode((string) file_get_contents(__DIR__ . '/rating.fixtures.json'), true, 64, JSON_THROW_ON_ERROR);

echo "<!-- GENERATED by test/ssr/build-rating-fixture.mjs from test/ssr/rating-fixture.php (php/td.php) — do not edit by hand. -->\n";
foreach ($spec['cases'] as $case) {
    echo '<section class="ssr-case" data-case="', Td::e($case['id']), '">', td_rating(...$case['args']), "</section>\n";
}
