<?php
/**
 * v0.38.0 — HTML fixture of src/form/td-scan-input.ssr.engines.browser-test.js: every case of
 * test/ssr/scan-input.fixtures.json rendered by td_scan_input(), each inside its own
 * `<form class="ssr-case|ssr-multiple|ssr-native" data-case="…">`. Regenerate with
 * `node test/ssr/build-scan-input-fixture.mjs` (test/php/td-ssr-scan-input.test.js fails when the file is stale).
 */
declare(strict_types=1);

require __DIR__ . '/../../php/td.php';

use TdComponents\Td;

Td::configure('/', dirname(__DIR__, 2));
$spec = json_decode((string) file_get_contents(__DIR__ . '/scan-input.fixtures.json'), true, 64, JSON_THROW_ON_ERROR);

echo "<!-- GENERATED by test/ssr/build-scan-input-fixture.mjs from test/ssr/scan-input-fixture.php (php/td.php) — do not edit by hand. -->\n";
foreach (['cases' => 'ssr-case', 'multipleCases' => 'ssr-multiple', 'nativeCases' => 'ssr-native'] as $key => $class) {
    foreach ($spec[$key] as $case) {
        echo '<form class="', $class, '" data-case="', Td::e($case['id']), '" action="/__ssr-submit" method="post">',
            td_scan_input(...$case['args']), "</form>\n";
    }
}
