<?php
/**
 * v0.45.0 — HTML fixtures of src/display/td-steps.ssr.engines.browser-test.js / td-timeline.ssr.engines.browser-test.js:
 * every case of test/ssr/{steps,timeline}.fixtures.json rendered by td_steps() / td_timeline(), each in its own
 * `<section class="ssr-case" data-case="…">`. argv[1] = steps | timeline. td_* warnings are swallowed (the PHP test
 * counts them). Regenerate with `node test/ssr/build-steps-timeline-fixture.mjs`.
 */
declare(strict_types=1);

require __DIR__ . '/../../php/td.php';

use TdComponents\Td;

date_default_timezone_set('UTC');
Td::configure('/', dirname(__DIR__, 2));
$which = ($argv[1] ?? '') === 'timeline' ? 'timeline' : 'steps';
$spec = json_decode((string) file_get_contents(__DIR__ . "/$which.fixtures.json"), true, 64, JSON_THROW_ON_ERROR);
set_error_handler(fn (int $no, string $msg): bool => $no === E_USER_WARNING && preg_match('/^td_(steps|timeline):/', $msg) === 1);

echo "<!-- GENERATED by test/ssr/build-steps-timeline-fixture.mjs from test/ssr/steps-timeline-fixture.php (php/td.php) — do not edit by hand. -->\n";
foreach ($spec['cases'] as $case) {
    $html = $which === 'timeline' ? td_timeline(...$case['args']) : td_steps(...$case['args']);
    echo '<section class="ssr-case" data-case="', Td::e($case['id']), '">', $html, "</section>\n";
}
