<?php
/**
 * v0.52.0 — HTML fixture of src/form/td-toggle.ssr.engines.browser-test.js: every case of test/ssr/toggle.fixtures.json
 * rendered by td_toggle() (tone / status_text / locked / locked_reason force element mode), each inside its own
 * `<form class="ssr-case" data-case="…">`; `externalLabel` → a `<label class="ext-label" for="{id}">` before the helper.
 * Regenerate with `node test/ssr/build-toggle-fixture.mjs` (test/php/td-v052-php.test.js fails when it is stale).
 */
declare(strict_types=1);

require __DIR__ . '/../../php/td.php';

use TdComponents\Td;

Td::configure('/', dirname(__DIR__, 2));
$spec = json_decode((string) file_get_contents(__DIR__ . '/toggle.fixtures.json'), true, 64, JSON_THROW_ON_ERROR);

echo "<!-- GENERATED by test/ssr/build-toggle-fixture.mjs from test/ssr/toggle-fixture.php (php/td.php) — do not edit by hand. -->\n";
foreach ($spec['cases'] as $case) {
    $ext = isset($case['externalLabel'])
        ? '<label class="ext-label" for="' . Td::e((string) $case['args'][3]['id']) . '">' . Td::e((string) $case['externalLabel']) . '</label>'
        : '';
    echo '<form class="ssr-case" data-case="', Td::e($case['id']), '" action="/__ssr-submit" method="post">',
        $ext, td_toggle(...$case['args']), "</form>\n";
}
