<?php
/**
 * v0.29.0 — HTML fixture of src/form/td-tree-select.ssr.engines.browser-test.js: every case of
 * test/ssr/tree-select.fixtures.json rendered by td_tree_select() in ELEMENT mode (per call `element => true`, or
 * `global` → Td::configure(..., ['ssr_elements' => true])), each inside its own `<form class="ssr-case" data-case="…">`,
 * plus the native cases (`<form class="ssr-native" …>`, default mode). An argument "@cats" / "@perms" is replaced by the
 * matching `trees` entry. Regenerate with `node test/ssr/build-tree-select-fixture.mjs`
 * (test/php/td-ssr-tree-select.test.js fails when test/ssr/fixtures/tree-select.html is stale).
 */
declare(strict_types=1);

require __DIR__ . '/../../php/td.php';

use TdComponents\Td;

$kit = dirname(__DIR__, 2);
$spec = json_decode((string) file_get_contents(__DIR__ . '/tree-select.fixtures.json'), true, 64, JSON_THROW_ON_ERROR);

/** "@name" arguments → the shared trees. */
function ssr_tree_args(array $args, array $trees): array
{
    foreach ($args as $i => $a) {
        if (is_string($a) && str_starts_with($a, '@') && isset($trees[substr($a, 1)])) {
            $args[$i] = $trees[substr($a, 1)];
        }
    }
    return $args;
}

/** Render one element-mode case (the options are the LAST argument). */
function ssr_tree_case(array $case, array $trees, string $kit): string
{
    $args = ssr_tree_args($case['args'], $trees);
    $last = count($args) - 1;
    if (!empty($case['global'])) {
        Td::configure('/', $kit, ['ssr_elements' => true]);
    } else {
        Td::configure('/', $kit);
        $args[$last]['element'] = true;
    }
    $html = td_tree_select(...$args);
    Td::configure('/', $kit);
    return $html;
}

Td::configure('/', $kit);
echo "<!-- GENERATED by test/ssr/build-tree-select-fixture.mjs from test/ssr/tree-select-fixture.php (php/td.php) — do not edit by hand. -->\n";
foreach ($spec['cases'] as $case) {
    echo '<form class="ssr-case" data-case="', Td::e($case['id']), '" action="/__ssr-submit" method="post">',
        ssr_tree_case($case, $spec['trees'], $kit), "</form>\n";
}
foreach ($spec['nativeCases'] as $case) {
    echo '<form class="ssr-native" data-case="', Td::e($case['id']), '" action="/__ssr-submit" method="post">',
        td_tree_select(...ssr_tree_args($case['args'], $spec['trees'])), "</form>\n";
}
