/**
 * Built-in presets (v0.42.0, owner decision): the kit's OWN light and dark values as explicit data — the generator never
 * re-derives them (generated palettes may differ, QĐ14), and the kit's CSS is never rewritten from a generator run.
 * Use: `npx td-theme --preset dark --name night` (the kit dark values under a site theme name), or presetPalette().
 * Values = what td.css renders (test/tokens/golden.json: v0.40 baseline + the v0.41 deltas / additions; dark
 * --td-accent-fill = the color-mix() result of engines that have it). Locked by palette.test.js.
 *
 * @module theme/presets
 */

/** Shadows / overlay / sheen per scheme — shared with the generator (identical to tokens.css / theme-dark.css). */
export const SCHEME_SHADOWS = Object.freeze({
  light: Object.freeze({
    '--td-shadow-1': '0 1px 2px rgb(0 0 0 / 6%)',
    '--td-shadow-2': '0 2px 8px rgb(0 0 0 / 8%)',
    '--td-shadow-3': '0 8px 24px rgb(0 0 0 / 12%)',
    '--td-glass-shadow': '0 2px 6px rgb(0 0 0 / 6%), 0 8px 24px rgb(0 0 0 / 12%)',
    '--td-glass-shadow-lg': '0 4px 12px rgb(0 0 0 / 8%), 0 20px 48px rgb(0 0 0 / 18%)',
    '--td-btn-lift': '0 1px 3px rgb(0 0 0 / 10%), 0 4px 10px -2px rgb(0 0 0 / 12%)',
  }),
  dark: Object.freeze({
    '--td-shadow-1': '0 1px 2px rgb(0 0 0 / 30%)',
    '--td-shadow-2': '0 2px 8px rgb(0 0 0 / 40%)',
    '--td-shadow-3': '0 8px 24px rgb(0 0 0 / 50%)',
    '--td-glass-shadow': '0 2px 6px rgb(0 0 0 / 24%), 0 8px 24px rgb(0 0 0 / 40%)',
    '--td-glass-shadow-lg': '0 4px 12px rgb(0 0 0 / 32%), 0 20px 48px rgb(0 0 0 / 56%)',
    '--td-btn-lift': '0 1px 3px rgb(0 0 0 / 20%), 0 4px 10px -2px rgb(0 0 0 / 24%)',
  }),
});

/** The kit focus ring (tokens.css): a 1px surface gap + a 2px solid --td-focus ring. */
export const FOCUS_RING = '0 0 0 1px var(--td-color-surface), 0 0 0 3px var(--td-focus)';

const COLOURS = {
  light: Object.freeze({
    '--td-color-bg': '#fbfbfa',
    '--td-color-surface': '#ffffff',
    '--td-color-surface-muted': '#f7f7f8',
    '--td-color-surface-raised': '#ffffff',
    '--td-control-bg': '#ffffff',
    '--td-glass-solid': '#ffffff',
    '--td-glass-bg': 'rgb(255 255 255 / 90%)',
    '--td-glass-bg-strong': 'rgb(255 255 255 / 94%)',
    '--td-color-text': '#1c1c1e',
    '--td-color-text-muted': '#6b6b73',
    '--td-color-text-subtle': '#8a8a93',
    '--td-color-text-label': '#45454b',
    '--td-control-fg': '#1c1c1e',
    '--td-glass-fg': '#18181b',
    '--td-color-border': '#e4e4e7',
    '--td-color-border-strong': '#d4d4d8',
    '--td-hairline': 'rgb(0 0 0 / 7%)',
    '--td-glass-border': 'rgb(0 0 0 / 7%)',
    '--td-control-border': '#d4d4d8',
    '--td-control-border-strong': '#8a8a93',
    '--td-control-border-soft': '#d1d1d6',
    '--td-control-border-hover': '#aeaeb2',
    '--td-focus': '#2563eb',
    '--td-focus-ring': FOCUS_RING,
    '--td-color-hover': 'rgb(0 0 0 / 5%)',
    '--td-color-hover-strong': 'rgb(0 0 0 / 8%)',
    '--td-color-pressed': 'rgb(0 0 0 / 12%)',
    '--td-color-skeleton': '#f0f0f2',
    '--td-color-sheen': 'rgb(255 255 255 / 60%)',
    '--td-color-fill': '#f0f0f2',
    '--td-color-fill-strong': '#ebebeb',
    '--td-color-on-fill': '#3f3f46',
    '--td-accent': '#2563eb',
    '--td-accent-fill': '#2563eb',
    '--td-accent-contrast': '#ffffff',
    '--td-color-success': '#15803d',
    '--td-color-warning': '#b45309',
    '--td-color-error': '#b91c1c',
    '--td-color-info': '#1d4ed8',
    '--td-color-on-status': '#ffffff',
    '--td-pastel-success-bg': '#dcfce7',
    '--td-pastel-success-border': '#bbf7d0',
    '--td-pastel-success-fg': '#14532d',
    '--td-pastel-danger-bg': '#fee2e2',
    '--td-pastel-danger-border': '#fecaca',
    '--td-pastel-danger-fg': '#7f1d1d',
    '--td-pastel-warning-bg': '#fef3c7',
    '--td-pastel-warning-border': '#fde68a',
    '--td-pastel-warning-fg': '#78350f',
    '--td-pastel-info-bg': '#dbeafe',
    '--td-pastel-info-border': '#bfdbfe',
    '--td-pastel-info-fg': '#1e3a8a',
    '--td-alert-success-bg': '#f0fdf4',
    '--td-alert-success-border': '#86efac',
    '--td-alert-success-icon': '#15803d',
    '--td-alert-warning-bg': '#fffbeb',
    '--td-alert-warning-border': '#fcd34d',
    '--td-alert-warning-icon': '#b45309',
    '--td-alert-danger-bg': '#fef2f2',
    '--td-alert-danger-border': '#fca5a5',
    '--td-alert-danger-icon': '#dc2626',
    '--td-alert-info-bg': '#eff6ff',
    '--td-alert-info-border': '#93c5fd',
    '--td-alert-info-icon': '#2563eb',
    '--td-btn-primary-bg': '#18181b',
    '--td-btn-primary-fg': '#ffffff',
    '--td-btn-primary-hover': '#3f3f46',
    '--td-btn-primary-pressed': '#52525b',
    '--td-btn-secondary-hover': '#e4e4e7',
    '--td-btn-secondary-pressed': '#d4d4d8',
    '--td-btn-secondary-border': 'rgb(0 0 0 / 12%)',
    '--td-btn-disabled-bg': '#f4f4f5',
    '--td-btn-disabled-fg': '#a1a1aa',
    '--td-btn-disabled-border': '#e4e4e7',
    '--td-color-overlay': 'rgb(10 10 12 / 45%)',
    '--td-tooltip-bg': '#18181b',
    '--td-tooltip-fg': '#ffffff',
    '--td-tooltip-border': 'transparent',
  }),
  dark: Object.freeze({
    '--td-color-bg': '#111113',
    '--td-color-surface': '#1c1c1e',
    '--td-color-surface-muted': '#242427',
    '--td-color-surface-raised': '#1c1c1e',
    '--td-control-bg': '#1c1c1e',
    '--td-glass-solid': '#1c1c1e',
    '--td-glass-bg': 'rgb(28 28 30 / 90%)',
    '--td-glass-bg-strong': 'rgb(28 28 30 / 94%)',
    '--td-color-text': '#f5f5f7',
    '--td-color-text-muted': '#acacb4',
    '--td-color-text-subtle': '#8a8a93',
    '--td-color-text-label': '#d4d4d8',
    '--td-control-fg': '#f5f5f7',
    '--td-glass-fg': '#f5f5f7',
    '--td-color-border': '#333338',
    '--td-color-border-strong': '#45454b',
    '--td-hairline': 'rgb(255 255 255 / 8%)',
    '--td-glass-border': 'rgb(255 255 255 / 14%)',
    '--td-control-border': '#45454b',
    '--td-control-border-strong': '#8a8a93',
    '--td-control-border-soft': '#76767c',
    '--td-control-border-hover': '#8e8e93',
    '--td-focus': '#60a5fa',
    '--td-focus-ring': FOCUS_RING,
    '--td-color-hover': 'rgb(255 255 255 / 6%)',
    '--td-color-hover-strong': 'rgb(255 255 255 / 10%)',
    '--td-color-pressed': 'rgb(255 255 255 / 14%)',
    '--td-color-skeleton': '#242427',
    '--td-color-sheen': 'rgb(255 255 255 / 8%)',
    '--td-color-fill': '#2c2c30',
    '--td-color-fill-strong': '#3c3c3e',
    '--td-color-on-fill': '#e4e4e7',
    '--td-accent': '#4b8df8',
    '--td-accent-fill': '#3c71c6',
    '--td-accent-contrast': '#ffffff',
    '--td-color-success': '#22c55e',
    '--td-color-warning': '#f59e0b',
    '--td-color-error': '#f87171',
    '--td-color-info': '#60a5fa',
    '--td-color-on-status': '#111113',
    '--td-pastel-success-bg': '#143121',
    '--td-pastel-success-border': '#16472a',
    '--td-pastel-success-fg': '#bbf7d0',
    '--td-pastel-danger-bg': '#391a1c',
    '--td-pastel-danger-border': '#542022',
    '--td-pastel-danger-fg': '#fecaca',
    '--td-pastel-warning-bg': '#3a2a12',
    '--td-pastel-warning-border': '#553b11',
    '--td-pastel-warning-fg': '#fde68a',
    '--td-pastel-info-bg': '#19253c',
    '--td-pastel-info-border': '#1e3357',
    '--td-pastel-info-fg': '#bfdbfe',
    '--td-alert-success-bg': '#0d2418',
    '--td-alert-success-border': '#14532d',
    '--td-alert-success-icon': '#86efac',
    '--td-alert-warning-bg': '#261b08',
    '--td-alert-warning-border': '#78350f',
    '--td-alert-warning-icon': '#fcd34d',
    '--td-alert-danger-bg': '#2a1111',
    '--td-alert-danger-border': '#7f1d1d',
    '--td-alert-danger-icon': '#fca5a5',
    '--td-alert-info-bg': '#111c33',
    '--td-alert-info-border': '#1e3a8a',
    '--td-alert-info-icon': '#93c5fd',
    '--td-btn-primary-bg': '#f4f4f5',
    '--td-btn-primary-fg': '#18181b',
    '--td-btn-primary-hover': '#d4d4d8',
    '--td-btn-primary-pressed': '#a1a1aa',
    '--td-btn-secondary-hover': '#3a3a3e',
    '--td-btn-secondary-pressed': '#45454b',
    '--td-btn-secondary-border': 'rgb(255 255 255 / 12%)',
    '--td-btn-disabled-bg': '#202024',
    '--td-btn-disabled-fg': '#6b6b73',
    '--td-btn-disabled-border': 'rgb(255 255 255 / 6%)',
    '--td-color-overlay': 'rgb(0 0 0 / 60%)',
    '--td-tooltip-bg': '#3a3a3e',
    '--td-tooltip-fg': '#ffffff',
    '--td-tooltip-border': 'rgb(255 255 255 / 16%)',
  }),

};

/**
 * v0.42.0 (impl review ISSUE-1): the kit's scheme-dependent COMPONENT tokens (tokens.js SCHEME_TOKENS) as rendered —
 * a preset under a name (no kit dark rule applies there) needs them too. color-mix() results are the static values of
 * engines that have it; the kit CSS itself is unchanged.
 */
const SCHEME_COMPONENTS = {
  light: {
    '--td-field-bg-disabled': '#f0f0f2',
    '--td-field-focus': '#467aee',
    '--td-field-focus-ring': '0 0 0 3px rgb(37 99 235 / 12%)',
    '--td-action-btn-warning-fg': '#b45309',
    '--td-action-btn-warning-hover-bg': '#fffbeb',
    '--td-action-btn-warning-pressed-bg': '#fef3c7',
    '--td-action-btn-warning-pressed-fg': '#92400e',
    '--td-action-btn-danger-fg': '#b91c1c',
    '--td-action-btn-danger-hover-bg': '#fee2e2',
    '--td-action-btn-danger-pressed-bg': '#fdd5d5',
    '--td-btn-ghost-hover-fg': '#1e51c1',
    '--td-btn-ghost-hover-fg-fallback': '#1d4ed8',
    '--td-slider-track': '#e4e4e7',
    '--td-slider-disabled': '#a1a1aa',
    '--td-tabs-pill': '#ffffff',
    '--td-tabs-pill-shadow': '0 1px 2px rgb(0 0 0 / 6%)',
    '--td-dropdown-create-fg': '#1e51c1',
    '--td-dropdown-create-fg-fallback': '#1d4ed8',
    '--td-table-zebra': 'rgb(0 0 0 / 2%)',
    '--td-table-row-selected': 'rgb(37 99 235 / 8%)',
    '--td-table-edge-shadow': 'rgb(0 0 0 / 14%)',
    '--td-form-summary-bg': '#f9eded',
    '--td-form-summary-border': '#cb5555',
    '--td-form-summary-pressed-bg': 'rgb(0 0 0 / 12%)',
    '--td-menu-separator': '#e4e4e7',
    '--td-chip-remove-hover': 'rgb(0 0 0 / 8%)',
    '--td-hovercard-error-fg': '#b91c1c',
    '--td-hovercard-link-fg': '#2563eb',
    '--td-dropzone-bg-active': '#f2f6fe',
    '--td-dropzone-bg-pressed': '#f4f4f5',
    '--td-badge-accent-bg': '#e0e9fc',
    '--td-badge-accent-fg': '#173d92',
    '--td-badge-success-ink': '#15803d',
    '--td-badge-warning-ink': '#b45309',
    '--td-badge-danger-ink': '#b91c1c',
    '--td-badge-info-ink': '#2563eb',
    '--td-filter-chip-remove-fg': '#45454b',
    '--td-diff-added-bg': '#eef6f1',
    '--td-diff-removed-bg': '#fbf2f2',
  },
  dark: {
    '--td-field-bg-disabled': '#242427',
    '--td-field-focus': '#669ef9',
    '--td-field-focus-ring': '0 0 0 3px rgb(75 141 248 / 22%)',
    '--td-action-btn-warning-fg': '#fcd34d',
    '--td-action-btn-warning-hover-bg': 'rgb(245 158 11 / 14%)',
    '--td-action-btn-warning-pressed-bg': 'rgb(245 158 11 / 26%)',
    '--td-action-btn-warning-pressed-fg': '#fcd34d',
    '--td-action-btn-danger-fg': '#fca5a5',
    '--td-action-btn-danger-hover-bg': 'rgb(220 38 38 / 18%)',
    '--td-action-btn-danger-pressed-bg': 'rgb(220 38 38 / 30%)',
    '--td-btn-ghost-hover-fg': '#81affa',
    '--td-btn-ghost-hover-fg-fallback': '#93c5fd',
    '--td-slider-track': '#3a3a40',
    '--td-slider-disabled': '#5a5a62',
    '--td-tabs-pill': 'rgb(255 255 255 / 14%)',
    '--td-tabs-pill-shadow': '0 1px 2px rgb(0 0 0 / 40%)',
    '--td-dropdown-create-fg': '#9cc0fb',
    '--td-dropdown-create-fg-fallback': '#93c5fd',
    '--td-table-zebra': 'rgb(255 255 255 / 3%)',
    '--td-table-row-selected': 'rgb(75 141 248 / 8%)',
    '--td-table-edge-shadow': 'rgb(0 0 0 / 55%)',
    '--td-form-summary-bg': '#362628',
    '--td-form-summary-border': '#c15c5c',
    '--td-form-summary-pressed-bg': 'rgb(0 0 0 / 40%)',
    '--td-menu-separator': 'rgb(255 255 255 / 12%)',
    '--td-chip-remove-hover': 'rgb(255 255 255 / 13%)',
    '--td-hovercard-error-fg': '#fca5a5',
    '--td-hovercard-link-fg': '#93c5fd',
    '--td-dropzone-bg-active': '#1f232b',
    '--td-dropzone-bg-pressed': '#2c2c30',
    '--td-badge-accent-bg': '#20314f',
    '--td-badge-accent-fg': '#b7d1fc',
    '--td-badge-success-ink': '#86efac',
    '--td-badge-warning-ink': '#fcd34d',
    '--td-badge-danger-ink': '#fca5a5',
    '--td-badge-info-ink': '#93c5fd',
    '--td-filter-chip-remove-fg': '#acacb4',
    '--td-diff-added-bg': '#1d3026',
    '--td-diff-removed-bg': '#362628',
  },
};

/** @type {Readonly<Record<'light'|'dark', Readonly<Record<string, string>>>>} THEME_TOKENS + SCHEME_TOKENS → CSS value */
export const PRESETS = Object.freeze({
  light: Object.freeze({ ...COLOURS.light, ...SCHEME_SHADOWS.light, ...SCHEME_COMPONENTS.light }),
  dark: Object.freeze({ ...COLOURS.dark, ...SCHEME_SHADOWS.dark, ...SCHEME_COMPONENTS.dark }),
});
