/**
 * Palette serializer (v0.42.0, plan N2) — one function for the CLI, the builder page and tests, so the three produce the
 * SAME bytes for the same seeds (differential test).
 *
 * `toCss(result, { acceptAaFailure })` → a static CSS file wrapped in `@layer td.tokens` with the selector of the
 * slot (selectors.js): `mode light` → the kit's base slot `:root, [data-td-theme]`; `mode dark` → the dark variant +
 * its `auto` copy under `@media (prefers-color-scheme: dark)`; a `name` → the variant `x` (`color-scheme` from the
 * computed scheme). Load order: td.css → this file → site CSS (same layer + same specificity as the kit slot, later
 * wins; the site's unlayered CSS still wins over both).
 *
 * Nothing from the raw input is ever copied: the header names the algorithm / contract versions and the seeds AS HEX
 * (re-serialised from numbers); the theme name passed the THEME_NAME_RE whitelist; token values are toCss() output or
 * fixed strings. Derived aliases equal to their source are left out (the kit alias keeps following the source).
 *
 * @module theme/serialize
 */
import { THEME_TOKENS } from './tokens.js';
import { BASE_SELECTOR, DARK_SELECTOR, AUTO_DARK_SELECTOR, AUTO_DARK_MEDIA, variantSelector } from './selectors.js';
import { redundantAliases, hasAaFailure, SEED_FIELDS } from './palette.js';

const HEX_RE = /^#[0-9a-f]{6}$/;

/** Mandatory failures as `CODE --token` (unique, generation order). */
function failureList(result) {
  const out = [];
  for (const d of result.diagnostics) {
    if (d.severity !== 'error-AA') continue;
    const s = `${d.code} ${d.token}`;
    if (!out.includes(s)) out.push(s);
  }
  return out;
}

/**
 * @param {ReturnType<import('./palette.js').generatePalette>} result
 * @param {{ acceptAaFailure?: boolean }} [o]
 * @returns {string}
 */
export function toCss(result, { acceptAaFailure = false } = {}) {
  const lines = [];
  if (hasAaFailure(result)) {
    const list = failureList(result).join(', ');
    lines.push(acceptAaFailure
      ? `/* td-theme: WARNING — mandatory WCAG AA failures accepted: ${list} */`
      : `/* td-theme: WARNING — mandatory WCAG AA failures (NOT accepted, td-theme exited 1): ${list} */`);
  }
  const seeds = Object.keys(SEED_FIELDS).filter((k) => typeof result.seeds[k] === 'string' && HEX_RE.test(result.seeds[k]))
    .map((k) => `${SEED_FIELDS[k].slice(2)} ${result.seeds[k]}`);
  lines.push('/*');
  lines.push(` * td-theme — generated by @dazzxq/td-components (palette algorithm ${result.algorithm}, THEME_TOKENS v${result.tokensVersion}).`);
  lines.push(' * Do not edit: regenerate with the same seeds after upgrading td-components (npx td-theme --version).');
  lines.push(result.preset ? ` * preset: ${result.preset === 'dark' ? 'dark' : 'light'}` : ` * seeds: ${seeds.join(' · ')}`);
  lines.push(` * mode ${result.mode === 'dark' ? 'dark' : 'light'}${result.name ? ` · name ${result.name}` : ''} · scheme ${result.scheme === 'dark' ? 'dark' : 'light'}`);
  lines.push(' * Load order: td.css → this file → site CSS.');
  lines.push(' */');

  const skip = redundantAliases(result.tokens);
  const decls = [`color-scheme: ${result.scheme === 'dark' ? 'dark' : 'light'};`];
  for (const t of THEME_TOKENS) {
    if (skip.has(t)) continue;
    decls.push(`${t}: ${result.tokens.get(t)};`);
  }
  const block = (selector, indent) => [`${indent}${selector} {`, ...decls.map((d) => `${indent}\t${d}`), `${indent}}`];
  const body = [];
  if (result.name) body.push(...block(variantSelector(result.name), '\t'));
  else if (result.mode === 'dark') {
    body.push(...block(DARK_SELECTOR, '\t'));
    body.push(`\t${AUTO_DARK_MEDIA} {`, ...block(AUTO_DARK_SELECTOR, '\t\t'), '\t}');
  } else body.push(...block(BASE_SELECTOR, '\t'));
  lines.push('@layer td.tokens {', ...body, '}');
  return `${lines.join('\n')}\n`;
}

/**
 * Normalised machine form (differential tests, `--diagnostics=json` adds the same diagnostics).
 * @param {ReturnType<import('./palette.js').generatePalette>} result
 */
export function toJson(result) {
  return {
    algorithm: result.algorithm,
    tokensVersion: result.tokensVersion,
    scheme: result.scheme,
    mode: result.mode,
    name: result.name,
    preset: result.preset || null,
    seeds: { ...result.seeds },
    tokens: Object.fromEntries(result.tokens),
    diagnostics: result.diagnostics.map((d) => ({ ...d, against: [...(d.against || [])] })),
  };
}

/** Human-readable diagnostics, one per line (CLI stderr, builder list). */
export function formatDiagnostics(result) {
  return result.diagnostics.map((d) => {
    const against = d.against && d.against.length ? ` on ${d.against.slice(0, 3).join(', ')}${d.against.length > 3 ? ` (+${d.against.length - 3})` : ''}` : '';
    const num = d.ratio !== null && d.ratio !== undefined ? `: ${d.ratio.toFixed(2)} < ${d.required}` : '';
    const extra = d.code === 'TD_THEME_ACCENT_ADJUSTED' ? `: ${d.from} → ${d.to}` : d.code === 'TD_THEME_APCA' ? `: Lc ${d.lc}` : '';
    return `${d.severity} ${d.code} ${d.token}${against}${num}${extra}`;
  });
}
