/* v0.42.0 R2-4 (plan N2): serialize.js — slot selectors from the selector table, THEME_TOKENS order, @layer td.tokens,
 * aliases left to the kit, the AA warning line, and no raw input anywhere in the output. */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { generatePalette, presetPalette, ThemeInputError } from './palette.js';
import { toCss, toJson, formatDiagnostics } from './serialize.js';
import { THEME_TOKENS } from './tokens.js';
import { BASE_SELECTOR, DARK_SELECTOR, AUTO_DARK_SELECTOR, variantSelector } from './selectors.js';
import { PRESETS } from './presets.js';

const beige = () => generatePalette({ bg: 'rgb(236, 229, 216)', accent: '#B3261E', surface: '#fff' });

test('light mode → the kit base slot inside @layer td.tokens, color-scheme first, tokens in contract order', () => {
  const css = toCss(beige());
  assert.match(css, /^\/\*\n \* td-theme — generated by @dazzxq\/td-components \(palette algorithm 1, THEME_TOKENS v1\)\./);
  assert.ok(css.includes(`@layer td.tokens {\n\t${BASE_SELECTOR} {\n\t\tcolor-scheme: light;\n\t\t--td-color-bg: #ece5d8;`));
  assert.equal(BASE_SELECTOR, ':root, [data-td-theme]');
  const order = [...css.matchAll(/\t(--td-[a-z0-9-]+):/g)].map((m) => m[1]);
  assert.deepEqual(order, THEME_TOKENS.filter((t) => order.includes(t)), 'contract order');
  assert.ok(css.endsWith('\t}\n}\n'));
  assert.equal((css.match(/\{/g) || []).length, (css.match(/\}/g) || []).length);
});

test('aliases equal to their source are left to the kit; diverging ones are written', () => {
  const css = toCss(beige());
  for (const t of ['--td-color-surface-raised', '--td-control-bg', '--td-glass-solid', '--td-control-fg', '--td-control-border']) {
    assert.ok(!css.includes(`\t${t}:`), `${t} omitted`);
  }
  const w = toCss(generatePalette({ bg: '#ece5d8', accent: '#b3261e', controlSurface: '#fff' }));
  assert.ok(w.includes('\t--td-control-bg: #ffffff;'));
  assert.ok(!w.includes('\t--td-glass-solid:'), 'glass-solid still follows raised');
});

test('dark mode → the dark variant + the generated auto copy (same declarations)', () => {
  const css = toCss(generatePalette({ bg: '#111113', accent: '#3b82f6' }, { mode: 'dark' }));
  assert.equal(DARK_SELECTOR, ':root[data-td-theme="dark"], [data-td-theme][data-td-theme="dark"]');
  assert.equal(AUTO_DARK_SELECTOR, ':root[data-td-theme="auto"], [data-td-theme][data-td-theme="auto"]');
  const dark = css.indexOf(`\t${DARK_SELECTOR} {`);
  const media = css.indexOf('\t@media (prefers-color-scheme: dark) {');
  const auto = css.indexOf(`\t\t${AUTO_DARK_SELECTOR} {`);
  assert.ok(dark > 0 && media > dark && auto > media);
  const body = (from) => css.slice(css.indexOf('{', from) + 1, css.indexOf('}', from)).replace(/\s+/g, ' ').trim();
  assert.equal(body(dark), body(auto));
  assert.ok(body(dark).startsWith('color-scheme: dark;'));
});

test('a named theme → its variant slot; names are whitelisted', () => {
  const css = toCss(generatePalette({ bg: '#ece5d8', accent: '#b3261e' }, { name: 'paper' }));
  assert.ok(css.includes(`\t${variantSelector('paper')} {`));
  assert.ok(css.includes(' * mode light · name paper · scheme light'));
  for (const bad of ['x"]{}*{color:red', 'dark', 'A', '../x']) {
    assert.throws(() => generatePalette({ bg: '#fff', accent: '#000' }, { name: bad }), ThemeInputError);
  }
  assert.throws(() => variantSelector('x"]'), TypeError);
});

test('no raw input reaches the CSS: seeds are re-serialised as hex, hostile strings are refused before', () => {
  const css = toCss(beige());
  assert.ok(css.includes(' * seeds: bg #ece5d8 · accent #b3261e · surface #ffffff'));
  assert.ok(!css.includes('rgb(236, 229, 216)') && !css.includes('B3261E'));
  for (const evil of ['#fff */ body{x:y} /*', '#fff;--td-x:1', '</style><script>', 'rgb(1,2,3)}', '#fff\n}', '#fff\u0000']) {
    assert.throws(() => generatePalette({ bg: evil, accent: '#000' }), ThemeInputError, JSON.stringify(evil));
  }
  // only one comment opener per comment: the header cannot be closed early
  for (const line of css.split('\n')) assert.ok((line.match(/\*\//g) || []).length <= 1);
});

test('AA failures: a conspicuous first line, accepted or not; only codes + token names', () => {
  const r = generatePalette({ bg: '#767676', accent: '#b3261e' });
  const no = toCss(r);
  const yes = toCss(r, { acceptAaFailure: true });
  assert.match(no.split('\n')[0], /^\/\* td-theme: WARNING — mandatory WCAG AA failures \(NOT accepted, td-theme exited 1\): TD_THEME_CONTRAST_UNSATISFIABLE --td-/);
  assert.match(yes.split('\n')[0], /^\/\* td-theme: WARNING — mandatory WCAG AA failures accepted: TD_THEME_CONTRAST_UNSATISFIABLE --td-color-[a-z]+(, TD_THEME_[A-Z_]+ --td-[a-z0-9-]+)* \*\/$/);
  assert.ok(!toCss(beige()).includes('WARNING'));
});

test('toJson / formatDiagnostics', () => {
  const j = toJson(generatePalette({ bg: '#767676', accent: '#b3261e' }));
  assert.equal(Object.keys(j.tokens).length, THEME_TOKENS.length);
  assert.ok(j.diagnostics.some((d) => d.code === 'TD_THEME_CONTRAST_UNSATISFIABLE' && d.severity === 'error-AA' && d.ratio < d.required));
  JSON.parse(JSON.stringify(j));
  const lines = formatDiagnostics(generatePalette({ bg: '#767676', accent: '#b3261e' }));
  assert.ok(lines.some((l) => /^error-AA TD_THEME_CONTRAST_UNSATISFIABLE --td-color-text on --td-color-bg, .*: \d\.\d\d < 4\.7$/.test(l)), lines.join('\n'));
});

test('presets serialise the kit values verbatim (shadows / ring = the CSS source strings)', () => {
  const css = toCss(presetPalette('dark', { name: 'night' }));
  assert.ok(css.includes(' * preset: dark'));
  assert.ok(css.includes(`\t--td-glass-shadow: ${PRESETS.dark['--td-glass-shadow']};`));
  assert.ok(css.includes('\t--td-focus-ring: 0 0 0 1px var(--td-color-surface), 0 0 0 3px var(--td-focus);'));
});
