#!/usr/bin/env node
/**
 * Generate src/icons/registry.js from the authored src/icons/icons.json (plain ESM for browsers
 * without JSON-module support; PHP adapters read the JSON directly).
 *   node scripts/build-icons.mjs          → write
 *   node scripts/build-icons.mjs --check  → exit 1 if stale
 */
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'src', 'icons', 'icons.json');
const OUT = join(ROOT, 'src', 'icons', 'registry.js');

const json = JSON.parse(await readFile(SRC, 'utf8'));
const icons = {};
for (const [name, def] of Object.entries(json.icons)) {
  icons[name] = { viewBox: def.viewBox, paint: def.paint, nodes: def.nodes };
}
// Aliases (v0.18.0): alternative name → core icon name. Must be a valid icon name, not shadow a core icon, and point
// at an existing core icon (no chains) — a bad entry fails the build instead of shipping a dead alias.
const NAME_RE = /^[a-z][a-z0-9-]{0,63}$/;
const aliases = {};
for (const [alias, target] of Object.entries(json.aliases ?? {})) {
  if (!NAME_RE.test(alias)) throw new Error(`icons.json aliases: invalid alias name "${alias}"`);
  if (Object.hasOwn(icons, alias)) throw new Error(`icons.json aliases: "${alias}" is already a core icon`);
  if (typeof target !== 'string' || !Object.hasOwn(icons, target)) {
    throw new Error(`icons.json aliases: "${alias}" → "${target}" is not a core icon`);
  }
  aliases[alias] = target;
}
const out = `/* GENERATED by scripts/build-icons.mjs from src/icons/icons.json — do not edit.\n`
  + ` * Geometry: Lucide (ISC; Feather-derived: MIT) — THIRD_PARTY_NOTICES.md. */\n`
  + `export default ${JSON.stringify(icons, null, 2)};\n\n`
  + `/** Alternative name → core icon name (icons.json "aliases"). */\n`
  + `export const aliases = ${JSON.stringify(aliases, null, 2)};\n`;

if (process.argv.includes('--check')) {
  let cur = '';
  try { cur = await readFile(OUT, 'utf8'); } catch { /* missing */ }
  if (cur !== out) { console.error('src/icons/registry.js is stale — run `npm run build:icons`.'); process.exit(1); }
  console.log('icons registry is up to date.');
} else {
  await writeFile(OUT, out);
  console.log(`src/icons/registry.js written (${Object.keys(icons).length} icons, ${Object.keys(aliases).length} aliases).`);
}
