#!/usr/bin/env node
/**
 * Build the canonical td.css from src/styles/ per manifest.json (deterministic concat).
 *   node scripts/build-css.mjs          → write td.css
 *   node scripts/build-css.mjs --check  → exit 1 if td.css is missing or stale
 * No preprocessing: sources are plain CSS; `@import` is rejected so the output is self-contained.
 */
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const STYLES = join(ROOT, 'src', 'styles');
const OUT = join(ROOT, 'td.css');

const manifest = JSON.parse(await readFile(join(STYLES, 'manifest.json'), 'utf8'));
if (manifest.files[0] !== 'layers.css') {
  throw new Error('manifest: layers.css must be first (it declares the layer order)');
}

const parts = [
  '/*! td.css — GENERATED by scripts/build-css.mjs from src/styles/ (manifest.json). Do not edit. */\n',
];
for (const file of manifest.files) {
  const css = (await readFile(join(STYLES, file), 'utf8')).replace(/\r\n/g, '\n').trimEnd();
  if (/^\s*@import\b/m.test(css)) throw new Error(`${file}: @import is not allowed (td.css must be self-contained)`);
  parts.push(`\n/* ---- src/styles/${file} ---- */\n${css}\n`);
}
const out = parts.join('');

if (process.argv.includes('--check')) {
  let current = '';
  try { current = await readFile(OUT, 'utf8'); } catch { /* missing */ }
  if (current !== out) {
    console.error('td.css is stale — run `npm run build:css` and commit the result.');
    process.exit(1);
  }
  console.log('td.css is up to date.');
} else {
  await writeFile(OUT, out);
  console.log(`td.css written (${out.length} bytes, ${manifest.files.length} files).`);
}
