#!/usr/bin/env node
/**
 * Generate src/icons/registry.js from the authored src/icons/icons.json (plain ESM for browsers
 * without JSON-module support; PHP adapters read the JSON directly).
 *   node scripts/build-icons.mjs          → write
 *   node scripts/build-icons.mjs --check  → exit 1 if stale
 */
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'src', 'icons', 'icons.json');
const OUT = join(ROOT, 'src', 'icons', 'registry.js');

const json = JSON.parse(await readFile(SRC, 'utf8'));
const icons = {};
for (const [name, def] of Object.entries(json.icons)) {
  icons[name] = { viewBox: def.viewBox, paint: def.paint, nodes: def.nodes };
}
const out = `/* GENERATED by scripts/build-icons.mjs from src/icons/icons.json — do not edit.\n`
  + ` * Geometry: Lucide (ISC; Feather-derived: MIT) — THIRD_PARTY_NOTICES.md. */\n`
  + `export default ${JSON.stringify(icons, null, 2)};\n`;

if (process.argv.includes('--check')) {
  let cur = '';
  try { cur = await readFile(OUT, 'utf8'); } catch { /* missing */ }
  if (cur !== out) { console.error('src/icons/registry.js is stale — run `npm run build:icons`.'); process.exit(1); }
  console.log('icons registry is up to date.');
} else {
  await writeFile(OUT, out);
  console.log(`src/icons/registry.js written (${Object.keys(icons).length} icons).`);
}
