#!/usr/bin/env node
/**
 * Build the canonical td.css from src/styles/ per manifest.json (deterministic concat).
 *   node scripts/build-css.mjs          → write td.css
 *   node scripts/build-css.mjs --check  → exit 1 if td.css is missing or stale
 * Sources are plain CSS; `@import` is rejected so the output is self-contained. ADR 0014 (v0.34.0): every `@media` /
 * `@container` must use a kit breakpoint, and each `@container td-*` block gets a generated `@supports not
 * (container-type: inline-size)` viewport fallback (scripts/css-responsive.mjs). ADR 0019 (v0.36.2): `:hover` only inside
 * `@media (hover: hover) and (pointer: fine)`, and every interactive control has a pressed (`:active` /
 * `[data-td-pressed]`) rule outside it (scripts/css-touch.mjs). v0.41.0 (theming QĐ4): every
 * `:root[data-td-theme="dark"]` rule gets a generated `@media (prefers-color-scheme: dark) { :root[data-td-theme="auto"] }`
 * copy right after it; hand-written auto rules are rejected (scripts/css-theme.mjs).
 */
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { checkBreakpoints, addContainerFallbacks, expandVariants } from './css-responsive.mjs';
import { checkHoverGate, checkPressed } from './css-touch.mjs';
import { expandAutoTheme } from './css-theme.mjs';



const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const STYLES = join(ROOT, 'src', 'styles');
const OUT = join(ROOT, 'td.css');

const manifest = JSON.parse(await readFile(join(STYLES, 'manifest.json'), 'utf8'));
if (manifest.files[0] !== 'layers.css') {
  throw new Error('manifest: layers.css must be first (it declares the layer order)');
}

const parts = [
  '/*! td.css — GENERATED by scripts/build-css.mjs from src/styles/ (manifest.json). Do not edit. */\n',
];
const bpErrors = [];
const touchErrors = [];
const touchEntries = [];
for (const file of manifest.files) {
  const css = (await readFile(join(STYLES, file), 'utf8')).replace(/\r\n/g, '\n').trimEnd();
  if (/^\s*@import\b/m.test(css)) throw new Error(`${file}: @import is not allowed (td.css must be self-contained)`);
  bpErrors.push(...checkBreakpoints(css, `src/styles/${file}`));
  touchErrors.push(...checkHoverGate(css, `src/styles/${file}`));
  touchEntries.push({ css, file: `src/styles/${file}` });
  let built;
  try {
    built = expandAutoTheme(addContainerFallbacks(expandVariants(css, `src/styles/${file}`), `src/styles/${file}`), `src/styles/${file}`);
  } catch (e) {
    console.error(e.message);
    process.exit(1);
  }
  parts.push(`\n/* ---- src/styles/${file} ---- */\n${built}\n`);
}
if (bpErrors.length) {
  console.error(`Breakpoints (ADR 0014):\n  ${bpErrors.join('\n  ')}`);
  process.exit(1);
}
touchErrors.push(...checkPressed(touchEntries));
if (touchErrors.length) {
  console.error(`Touch (ADR 0019):\n  ${touchErrors.join('\n  ')}\n  (${touchErrors.length} errors)`);
  process.exit(1);
}
const out = parts.join('');

if (process.argv.includes('--check')) {
  let current = '';
  try { current = await readFile(OUT, 'utf8'); } catch { /* missing */ }
  if (current !== out) {
    console.error('td.css is stale — run `npm run build:css` and commit the result.');
    process.exit(1);
  }
  console.log('td.css is up to date.');
} else {
  await writeFile(OUT, out);
  console.log(`td.css written (${out.length} bytes, ${manifest.files.length} files).`);
}
