<?php
/**
 * HTML fixture of src/form/td-v017-ssr.browser-test.js, rendered by php/td.php. Regenerate with
 * `node test/php/build-fixture.mjs` (test/php/td-php.test.js fails when test/php/fixtures/ssr.html is stale).
 */
declare(strict_types=1);

require __DIR__ . '/../../php/td.php';

use TdComponents\Td;

Td::configure('/', dirname(__DIR__, 2));

$parity = [
    'btn-primary' => td_button('Lưu', ['variant' => 'primary', 'icon' => 'download']),
    'btn-secondary-sm' => td_button('Huỷ', ['variant' => 'secondary', 'size' => 'sm']),
    'btn-danger-lg' => td_button('Xoá', ['variant' => 'danger', 'size' => 'lg', 'icon' => 'close', 'icon_position' => 'right']),
    'btn-disabled' => td_button('Khoá', ['variant' => 'primary', 'disabled' => true]),
    'btn-ghost' => td_button('Bỏ qua', ['variant' => 'ghost']),
    'btn-link' => td_button('Mở', ['variant' => 'primary', 'href' => '/docs', 'target' => '_blank']),
    'field-text' => td_field('full_name', 'An', ['label' => 'Họ tên', 'hint' => 'Tên đầy đủ', 'id' => 'pf-text']),
    'field-lg' => td_field('email', 'a@b.vn', ['label' => 'Email', 'size' => 'lg', 'id' => 'pf-lg']),
    'field-area' => td_field('bio', 'Xin chào', ['label' => 'Mô tả', 'type' => 'textarea', 'rows' => 3, 'id' => 'pf-area']),
    'check-on' => td_checkbox('c1', true, 'Đồng ý'),
    'check-sm' => td_checkbox('c2', false, 'Nhỏ', ['size' => 'sm']),
    'toggle-on' => td_toggle('t1', true, 'Wifi'),
    'toggle-lg' => td_toggle('t2', false, 'Lớn', ['size' => 'lg']),
];
?>
<!-- GENERATED by test/php/build-fixture.mjs from test/php/fixture.php (php/td.php) — do not edit by hand. -->
<form id="ssr-form" action="#" method="post">
<?= td_field('full_name', 'Nguyễn An', ['label' => 'Họ tên', 'required' => true, 'id' => 'f-name']) ?>

<?= td_field('password', 'bí-mật-1', ['label' => 'Mật khẩu', 'type' => 'password', 'autocomplete' => 'current-password', 'required' => true, 'id' => 'f-pw']) ?>

<?= td_field('month', '2026-09', ['label' => 'Tháng', 'type' => 'month', 'id' => 'f-month']) ?>

<?= td_field('taken_at', '2026-09-28T10:30', ['label' => 'Ngày giờ', 'type' => 'datetime-local', 'id' => 'f-dt']) ?>

<?= td_checkbox('agree', true, 'Đồng ý', ['value' => 'yes']) ?>

<?= td_checkbox('newsletter', false, 'Nhận tin') ?>

<?= td_toggle('wifi', true, 'Wifi') ?>

<?= td_toggle('bluetooth', false, 'Bluetooth') ?>

<?= td_dropdown('city', ['hn' => 'Hà Nội', 'sg' => 'Sài Gòn', 'dn' => 'Đà Nẵng'], 'sg', ['label' => 'Thành phố', 'required' => true, 'id' => 'dd-city']) ?>

<?= td_button('Lưu', ['type' => 'submit', 'name' => 'action', 'value' => 'save', 'variant' => 'primary', 'id' => 'btn-save']) ?>

<?= td_button('Xoá', ['type' => 'submit', 'name' => 'action', 'value' => 'delete', 'variant' => 'danger', 'id' => 'btn-delete']) ?>

</form>
<div id="ssr-parity">
<?php foreach ($parity as $key => $html): ?>
<div class="ssr-p" data-p="<?= Td::e($key) ?>"><?= $html ?></div>
<?php endforeach; ?>
</div>
