import '../form/td-datetime-picker.js';
import '../form/td-datetime-range.js';

/**
 * v0.60.0 (plan v0.60.0-calendar-picker C1, acceptance 8) + v0.61.0 (plan v0.61.0-range-calendar, acceptance 10): what must NOT
 * change while the calendar dialogs are redesigned and the implicit 2000–2099 year window goes away: the CLOSED box of
 * <td-datetime-picker> (every mode, clearable, error, disabled, required) and of <td-datetime-range> (date / datetime / open end /
 * empty) — character-identical to the v0.59.0 markup. (The range DIALOG was character-identical in v0.60.0 and was redesigned in
 * v0.61.0 on purpose: its contract is now the a11y spec + the selector contract of docs/components/datetime-range.md.)
 * `CAPTURES` builds each case; td-v060-baseline.engines.browser-test.js compares it with `BASELINE` (captured from v0.59.0
 * `1f2c985`; the range ones from v0.60.0 `29f35dd`, whose closed box is byte-equal to v0.59.0's). Generated ids are normalised.
 */
const frames = (n = 2) => new Promise((r) => { const f = (k) => (k ? requestAnimationFrame(() => f(k - 1)) : r()); f(n); });
const norm = (html) => html.replace(/td-modal-\d+(-[a-z0-9]+)?/g, 'td-modal-N').replace(/-dtr\d+/g, '-dtrN').replace(/-dtp\d+/g, '-dtpN');

async function host(html, setup) {
  const wrap = document.createElement('div');
  wrap.style.width = '900px';
  wrap.innerHTML = html;
  document.body.appendChild(wrap);
  const el = wrap.firstElementChild;
  if (setup) setup(el);
  await frames(3);
  const out = norm(el.outerHTML);
  wrap.remove();
  return out;
}

export const CAPTURES = {
  'picker-datetime': () => host('<td-datetime-picker id="p1" label="Hẹn" value="15/06/2026 - 09:30"></td-datetime-picker>'),
  'picker-date': () => host('<td-datetime-picker id="p2" mode="date" label="Ngày" value="15/06/2026"></td-datetime-picker>'),
  'picker-month': () => host('<td-datetime-picker id="p3" mode="month" label="Tháng" value="06/2026"></td-datetime-picker>'),
  'picker-year': () => host('<td-datetime-picker id="p4" mode="year" aria-label="Năm" value="2026"></td-datetime-picker>'),
  'picker-empty-required': () => host('<td-datetime-picker id="p5" mode="date" label="Hạn" required></td-datetime-picker>'),
  'picker-clearable': () => host('<td-datetime-picker id="p6" mode="date" label="Hạn" value="15/06/2026" clearable></td-datetime-picker>'),
  'picker-clearable-empty': () => host('<td-datetime-picker id="p7" mode="date" label="Hạn" clearable></td-datetime-picker>'),
  'picker-error': () => host('<td-datetime-picker id="p8" mode="date" label="Ngày" value="15/06/2026" error-text="Sai ngày"></td-datetime-picker>'),
  'picker-disabled': () => host('<td-datetime-picker id="p9" label="Khoá" value="15/06/2026 - 09:30" disabled></td-datetime-picker>'),
  'picker-bounds-helper': () => host('<td-datetime-picker id="p10" mode="date" label="Ngày" min="2026-01-01" max="2026-12-31" helper-text="Trong năm"></td-datetime-picker>'),
  'range-closed-date': () => host('<td-datetime-range id="rc1" label="Khoảng" start="01/10/2026" end="05/10/2026" name="rc"></td-datetime-range>'),
  'range-closed-datetime': () => host('<td-datetime-range id="rc2" mode="datetime" label="Khung giờ" start="01/10/2026 - 08:00" end="05/10/2026 - 17:30" minute-step="15"></td-datetime-range>'),
  'range-closed-open-end': () => host('<td-datetime-range id="rc3" label="Hạn" start="01/10/2026" allow-open-end required></td-datetime-range>'),
  'range-closed-empty-required': () => host('<td-datetime-range id="rc4" required="end" placeholder="Chọn khoảng"></td-datetime-range>'),
  'range-closed-error': () => host('<td-datetime-range id="rc5" label="Khoảng" start="01/10/2026" error-text="Sai khoảng"></td-datetime-range>'),
  'range-closed-disabled': () => host('<td-datetime-range id="rc6" label="Khoá" start="01/10/2026" end="05/10/2026" disabled></td-datetime-range>'),
};

/** v0.59.0 markup of every CAPTURES case — the picker ones captured at `1f2c985` (3 engines, identical) before any v0.60.0 change; the `range-closed-*` ones at v0.60.0 `29f35dd` (Chromium; the closed range box is byte-equal to v0.59.0's) before any v0.61.0 change. */
export const BASELINE = {
  "picker-datetime": "<td-datetime-picker id=\"p1\" label=\"Hẹn\" value=\"15/06/2026 - 09:30\"><div class=\"td-dtp\" data-state=\"closed\"><label class=\"td-field__label\" id=\"p1-label\" for=\"p1-trigger\">Hẹn</label><button type=\"button\" class=\"td-dtp__trigger\" id=\"p1-trigger\" role=\"combobox\" aria-haspopup=\"dialog\" aria-expanded=\"false\"><span class=\"td-dtp__value\">15/06/2026 - 09:30</span><span class=\"td-dtp__icon\" data-td-icon=\"calendar\" aria-hidden=\"true\"><svg class=\"td-icon td-icon--m\" data-icon=\"calendar\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\" focusable=\"false\"><path d=\"M8 2v4\"></path><path d=\"M16 2v4\"></path><rect x=\"3\" y=\"4\" width=\"18\" height=\"18\" rx=\"2\"></rect><path d=\"M3 10h18\"></path></svg></span></button></div></td-datetime-picker>",
  "picker-date": "<td-datetime-picker id=\"p2\" mode=\"date\" label=\"Ngày\" value=\"15/06/2026\"><div class=\"td-dtp\" data-state=\"closed\"><label class=\"td-field__label\" id=\"p2-label\" for=\"p2-trigger\">Ngày</label><button type=\"button\" class=\"td-dtp__trigger\" id=\"p2-trigger\" role=\"combobox\" aria-haspopup=\"dialog\" aria-expanded=\"false\"><span class=\"td-dtp__value\">15/06/2026</span><span class=\"td-dtp__icon\" data-td-icon=\"calendar\" aria-hidden=\"true\"><svg class=\"td-icon td-icon--m\" data-icon=\"calendar\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\" focusable=\"false\"><path d=\"M8 2v4\"></path><path d=\"M16 2v4\"></path><rect x=\"3\" y=\"4\" width=\"18\" height=\"18\" rx=\"2\"></rect><path d=\"M3 10h18\"></path></svg></span></button></div></td-datetime-picker>",
  "picker-month": "<td-datetime-picker id=\"p3\" mode=\"month\" label=\"Tháng\" value=\"06/2026\"><div class=\"td-dtp\" data-state=\"closed\"><label class=\"td-field__label\" id=\"p3-label\" for=\"p3-trigger\">Tháng</label><button type=\"button\" class=\"td-dtp__trigger\" id=\"p3-trigger\" role=\"combobox\" aria-haspopup=\"dialog\" aria-expanded=\"false\"><span class=\"td-dtp__value\">06/2026</span><span class=\"td-dtp__icon\" data-td-icon=\"calendar\" aria-hidden=\"true\"><svg class=\"td-icon td-icon--m\" data-icon=\"calendar\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\" focusable=\"false\"><path d=\"M8 2v4\"></path><path d=\"M16 2v4\"></path><rect x=\"3\" y=\"4\" width=\"18\" height=\"18\" rx=\"2\"></rect><path d=\"M3 10h18\"></path></svg></span></button></div></td-datetime-picker>",
  "picker-year": "<td-datetime-picker id=\"p4\" mode=\"year\" aria-label=\"Năm\" value=\"2026\"><div class=\"td-dtp\" data-state=\"closed\"><button type=\"button\" class=\"td-dtp__trigger\" id=\"p4-trigger\" role=\"combobox\" aria-haspopup=\"dialog\" aria-expanded=\"false\" aria-label=\"Năm\"><span class=\"td-dtp__value\">2026</span><span class=\"td-dtp__icon\" data-td-icon=\"calendar\" aria-hidden=\"true\"><svg class=\"td-icon td-icon--m\" data-icon=\"calendar\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\" focusable=\"false\"><path d=\"M8 2v4\"></path><path d=\"M16 2v4\"></path><rect x=\"3\" y=\"4\" width=\"18\" height=\"18\" rx=\"2\"></rect><path d=\"M3 10h18\"></path></svg></span></button></div></td-datetime-picker>",
  "picker-empty-required": "<td-datetime-picker id=\"p5\" mode=\"date\" label=\"Hạn\" required=\"\"><div class=\"td-dtp\" data-state=\"closed\"><label class=\"td-field__label\" id=\"p5-label\" for=\"p5-trigger\">Hạn<span class=\"td-field__required\" aria-hidden=\"true\"> *</span></label><button type=\"button\" class=\"td-dtp__trigger\" id=\"p5-trigger\" role=\"combobox\" aria-haspopup=\"dialog\" aria-expanded=\"false\" aria-required=\"true\"><span class=\"td-dtp__value\" data-placeholder=\"\">dd/mm/yyyy</span><span class=\"td-dtp__icon\" data-td-icon=\"calendar\" aria-hidden=\"true\"><svg class=\"td-icon td-icon--m\" data-icon=\"calendar\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\" focusable=\"false\"><path d=\"M8 2v4\"></path><path d=\"M16 2v4\"></path><rect x=\"3\" y=\"4\" width=\"18\" height=\"18\" rx=\"2\"></rect><path d=\"M3 10h18\"></path></svg></span></button></div></td-datetime-picker>",
  "picker-clearable": "<td-datetime-picker id=\"p6\" mode=\"date\" label=\"Hạn\" value=\"15/06/2026\" clearable=\"\"><div class=\"td-dtp td-dtp--clearable\" data-state=\"closed\"><label class=\"td-field__label\" id=\"p6-label\" for=\"p6-trigger\">Hạn</label><button type=\"button\" class=\"td-dtp__trigger\" id=\"p6-trigger\" role=\"combobox\" aria-haspopup=\"dialog\" aria-expanded=\"false\"><span class=\"td-dtp__value\">15/06/2026</span><span class=\"td-dtp__icon\" data-td-icon=\"calendar\" aria-hidden=\"true\"><svg class=\"td-icon td-icon--m\" data-icon=\"calendar\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\" focusable=\"false\"><path d=\"M8 2v4\"></path><path d=\"M16 2v4\"></path><rect x=\"3\" y=\"4\" width=\"18\" height=\"18\" rx=\"2\"></rect><path d=\"M3 10h18\"></path></svg></span></button><button type=\"button\" class=\"td-dtp__clear\" aria-label=\"Xoá ngày\"><span class=\"td-dtp__clear-icon\" data-td-icon=\"close\" data-td-icon-size=\"s\" aria-hidden=\"true\"><svg class=\"td-icon td-icon--s\" data-icon=\"close\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\" focusable=\"false\"><path d=\"M18 6 6 18\"></path><path d=\"m6 6 12 12\"></path></svg></span></button></div></td-datetime-picker>",
  "picker-clearable-empty": "<td-datetime-picker id=\"p7\" mode=\"date\" label=\"Hạn\" clearable=\"\"><div class=\"td-dtp td-dtp--clearable\" data-state=\"closed\"><label class=\"td-field__label\" id=\"p7-label\" for=\"p7-trigger\">Hạn</label><button type=\"button\" class=\"td-dtp__trigger\" id=\"p7-trigger\" role=\"combobox\" aria-haspopup=\"dialog\" aria-expanded=\"false\"><span class=\"td-dtp__value\" data-placeholder=\"\">dd/mm/yyyy</span><span class=\"td-dtp__icon\" data-td-icon=\"calendar\" aria-hidden=\"true\"><svg class=\"td-icon td-icon--m\" data-icon=\"calendar\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\" focusable=\"false\"><path d=\"M8 2v4\"></path><path d=\"M16 2v4\"></path><rect x=\"3\" y=\"4\" width=\"18\" height=\"18\" rx=\"2\"></rect><path d=\"M3 10h18\"></path></svg></span></button><button type=\"button\" class=\"td-dtp__clear\" aria-label=\"Xoá ngày\" hidden=\"\"><span class=\"td-dtp__clear-icon\" data-td-icon=\"close\" data-td-icon-size=\"s\" aria-hidden=\"true\"><svg class=\"td-icon td-icon--s\" data-icon=\"close\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\" focusable=\"false\"><path d=\"M18 6 6 18\"></path><path d=\"m6 6 12 12\"></path></svg></span></button></div></td-datetime-picker>",
  "picker-error": "<td-datetime-picker id=\"p8\" mode=\"date\" label=\"Ngày\" value=\"15/06/2026\" error-text=\"Sai ngày\"><div class=\"td-dtp\" data-state=\"closed\"><label class=\"td-field__label\" id=\"p8-label\" for=\"p8-trigger\">Ngày</label><button type=\"button\" class=\"td-dtp__trigger\" id=\"p8-trigger\" role=\"combobox\" aria-haspopup=\"dialog\" aria-expanded=\"false\" aria-invalid=\"true\" aria-errormessage=\"p8-error\" aria-describedby=\"p8-error\"><span class=\"td-dtp__value\">15/06/2026</span><span class=\"td-dtp__icon\" data-td-icon=\"calendar\" aria-hidden=\"true\"><svg class=\"td-icon td-icon--m\" data-icon=\"calendar\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\" focusable=\"false\"><path d=\"M8 2v4\"></path><path d=\"M16 2v4\"></path><rect x=\"3\" y=\"4\" width=\"18\" height=\"18\" rx=\"2\"></rect><path d=\"M3 10h18\"></path></svg></span></button></div><span class=\"td-field-error\" id=\"p8-error\" data-for=\"p8\">Sai ngày</span></td-datetime-picker>",
  "picker-disabled": "<td-datetime-picker id=\"p9\" label=\"Khoá\" value=\"15/06/2026 - 09:30\" disabled=\"\"><div class=\"td-dtp\" data-state=\"closed\"><label class=\"td-field__label\" id=\"p9-label\" for=\"p9-trigger\">Khoá</label><button type=\"button\" class=\"td-dtp__trigger\" id=\"p9-trigger\" role=\"combobox\" aria-haspopup=\"dialog\" aria-expanded=\"false\" disabled=\"\"><span class=\"td-dtp__value\">15/06/2026 - 09:30</span><span class=\"td-dtp__icon\" data-td-icon=\"calendar\" aria-hidden=\"true\"><svg class=\"td-icon td-icon--m\" data-icon=\"calendar\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\" focusable=\"false\"><path d=\"M8 2v4\"></path><path d=\"M16 2v4\"></path><rect x=\"3\" y=\"4\" width=\"18\" height=\"18\" rx=\"2\"></rect><path d=\"M3 10h18\"></path></svg></span></button></div></td-datetime-picker>",
  "picker-bounds-helper": "<td-datetime-picker id=\"p10\" mode=\"date\" label=\"Ngày\" min=\"2026-01-01\" max=\"2026-12-31\" helper-text=\"Trong năm\"><div class=\"td-dtp\" data-state=\"closed\"><label class=\"td-field__label\" id=\"p10-label\" for=\"p10-trigger\">Ngày</label><button type=\"button\" class=\"td-dtp__trigger\" id=\"p10-trigger\" role=\"combobox\" aria-haspopup=\"dialog\" aria-expanded=\"false\" aria-describedby=\"p10-note\"><span class=\"td-dtp__value\" data-placeholder=\"\">dd/mm/yyyy</span><span class=\"td-dtp__icon\" data-td-icon=\"calendar\" aria-hidden=\"true\"><svg class=\"td-icon td-icon--m\" data-icon=\"calendar\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\" focusable=\"false\"><path d=\"M8 2v4\"></path><path d=\"M16 2v4\"></path><rect x=\"3\" y=\"4\" width=\"18\" height=\"18\" rx=\"2\"></rect><path d=\"M3 10h18\"></path></svg></span></button></div><div class=\"td-field__note\" id=\"p10-note\">Trong năm</div></td-datetime-picker>",
  "range-closed-date": "<td-datetime-range id=\"rc1\" label=\"Khoảng\" start=\"01/10/2026\" end=\"05/10/2026\" name=\"rc\"><div class=\"td-dtr\" data-state=\"closed\"><span class=\"td-field__label td-dtr__label\" id=\"rc1-label\">Khoảng</span><button type=\"button\" class=\"td-dtr__trigger\" id=\"rc1-trigger\" role=\"combobox\" aria-haspopup=\"dialog\" aria-expanded=\"false\" aria-labelledby=\"rc1-label\"><span class=\"td-dtr__value\">01/10/2026 – 05/10/2026</span><span class=\"td-dtr__icon\" data-td-icon=\"calendar\" aria-hidden=\"true\"><svg class=\"td-icon td-icon--m\" data-icon=\"calendar\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\" focusable=\"false\"><path d=\"M8 2v4\"></path><path d=\"M16 2v4\"></path><rect x=\"3\" y=\"4\" width=\"18\" height=\"18\" rx=\"2\"></rect><path d=\"M3 10h18\"></path></svg></span></button></div></td-datetime-range>",
  "range-closed-datetime": "<td-datetime-range id=\"rc2\" mode=\"datetime\" label=\"Khung giờ\" start=\"01/10/2026 - 08:00\" end=\"05/10/2026 - 17:30\" minute-step=\"15\"><div class=\"td-dtr\" data-state=\"closed\"><span class=\"td-field__label td-dtr__label\" id=\"rc2-label\">Khung giờ</span><button type=\"button\" class=\"td-dtr__trigger\" id=\"rc2-trigger\" role=\"combobox\" aria-haspopup=\"dialog\" aria-expanded=\"false\" aria-labelledby=\"rc2-label\"><span class=\"td-dtr__value\">01/10/2026 - 08:00 – 05/10/2026 - 17:30</span><span class=\"td-dtr__icon\" data-td-icon=\"calendar\" aria-hidden=\"true\"><svg class=\"td-icon td-icon--m\" data-icon=\"calendar\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\" focusable=\"false\"><path d=\"M8 2v4\"></path><path d=\"M16 2v4\"></path><rect x=\"3\" y=\"4\" width=\"18\" height=\"18\" rx=\"2\"></rect><path d=\"M3 10h18\"></path></svg></span></button></div></td-datetime-range>",
  "range-closed-open-end": "<td-datetime-range id=\"rc3\" label=\"Hạn\" start=\"01/10/2026\" allow-open-end=\"\" required=\"\"><div class=\"td-dtr\" data-state=\"closed\"><span class=\"td-field__label td-dtr__label\" id=\"rc3-label\">Hạn<span class=\"td-field__required\" aria-hidden=\"true\"> *</span></span><button type=\"button\" class=\"td-dtr__trigger\" id=\"rc3-trigger\" role=\"combobox\" aria-haspopup=\"dialog\" aria-expanded=\"false\" aria-labelledby=\"rc3-label\" aria-required=\"true\"><span class=\"td-dtr__value\">01/10/2026 – Không hạn</span><span class=\"td-dtr__icon\" data-td-icon=\"calendar\" aria-hidden=\"true\"><svg class=\"td-icon td-icon--m\" data-icon=\"calendar\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\" focusable=\"false\"><path d=\"M8 2v4\"></path><path d=\"M16 2v4\"></path><rect x=\"3\" y=\"4\" width=\"18\" height=\"18\" rx=\"2\"></rect><path d=\"M3 10h18\"></path></svg></span></button></div></td-datetime-range>",
  "range-closed-empty-required": "<td-datetime-range id=\"rc4\" required=\"end\" placeholder=\"Chọn khoảng\"><div class=\"td-dtr\" data-state=\"closed\"><button type=\"button\" class=\"td-dtr__trigger\" id=\"rc4-trigger\" role=\"combobox\" aria-haspopup=\"dialog\" aria-expanded=\"false\" aria-required=\"true\"><span class=\"td-dtr__value\" data-placeholder=\"\">Chọn khoảng</span><span class=\"td-dtr__icon\" data-td-icon=\"calendar\" aria-hidden=\"true\"><svg class=\"td-icon td-icon--m\" data-icon=\"calendar\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\" focusable=\"false\"><path d=\"M8 2v4\"></path><path d=\"M16 2v4\"></path><rect x=\"3\" y=\"4\" width=\"18\" height=\"18\" rx=\"2\"></rect><path d=\"M3 10h18\"></path></svg></span></button></div></td-datetime-range>",
  "range-closed-error": "<td-datetime-range id=\"rc5\" label=\"Khoảng\" start=\"01/10/2026\" error-text=\"Sai khoảng\"><div class=\"td-dtr\" data-state=\"closed\"><span class=\"td-field__label td-dtr__label\" id=\"rc5-label\">Khoảng</span><button type=\"button\" class=\"td-dtr__trigger\" id=\"rc5-trigger\" role=\"combobox\" aria-haspopup=\"dialog\" aria-expanded=\"false\" aria-labelledby=\"rc5-label\" aria-invalid=\"true\" aria-errormessage=\"rc5-error\" aria-describedby=\"rc5-error\"><span class=\"td-dtr__value\">Từ 01/10/2026</span><span class=\"td-dtr__icon\" data-td-icon=\"calendar\" aria-hidden=\"true\"><svg class=\"td-icon td-icon--m\" data-icon=\"calendar\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\" focusable=\"false\"><path d=\"M8 2v4\"></path><path d=\"M16 2v4\"></path><rect x=\"3\" y=\"4\" width=\"18\" height=\"18\" rx=\"2\"></rect><path d=\"M3 10h18\"></path></svg></span></button></div><span class=\"td-field-error\" id=\"rc5-error\" data-for=\"rc5\">Sai khoảng</span></td-datetime-range>",
  "range-closed-disabled": "<td-datetime-range id=\"rc6\" label=\"Khoá\" start=\"01/10/2026\" end=\"05/10/2026\" disabled=\"\"><div class=\"td-dtr\" data-state=\"closed\"><span class=\"td-field__label td-dtr__label\" id=\"rc6-label\">Khoá</span><button type=\"button\" class=\"td-dtr__trigger\" id=\"rc6-trigger\" role=\"combobox\" aria-haspopup=\"dialog\" aria-expanded=\"false\" aria-labelledby=\"rc6-label\" disabled=\"\"><span class=\"td-dtr__value\">01/10/2026 – 05/10/2026</span><span class=\"td-dtr__icon\" data-td-icon=\"calendar\" aria-hidden=\"true\"><svg class=\"td-icon td-icon--m\" data-icon=\"calendar\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\" focusable=\"false\"><path d=\"M8 2v4\"></path><path d=\"M16 2v4\"></path><rect x=\"3\" y=\"4\" width=\"18\" height=\"18\" rx=\"2\"></rect><path d=\"M3 10h18\"></path></svg></span></button></div></td-datetime-range>",
};
